<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jair Malta e Wesley Pinheiro">

<title>Relatório de Aula Prática 01 - Teste</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="index_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="index_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">1</span> 📌 Introdução</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos"><span class="header-section-number">2</span> 🎯 Objetivos</a>
  <ul class="collapse">
  <li><a href="#objetivo-geral" id="toc-objetivo-geral" class="nav-link" data-scroll-target="#objetivo-geral"><span class="header-section-number">2.1</span> Objetivo geral</a></li>
  <li><a href="#objetivos-específicos" id="toc-objetivos-específicos" class="nav-link" data-scroll-target="#objetivos-específicos"><span class="header-section-number">2.2</span> Objetivos específicos</a></li>
  </ul></li>
  <li><a href="#metodologia" id="toc-metodologia" class="nav-link" data-scroll-target="#metodologia"><span class="header-section-number">3</span> ⚙️ Metodologia</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">
<div class="logos" style="display: flex; justify-content: center; align-items: center; height: 200px; gap: 20px;">

  <a href="https://ufsj.edu.br">

    <img src="imagens/ufsj.png" width="220px">

  </a>

  <a href="https://ufsj.edu.br/defim">

    <img src="imagens/defim.png" width="220px">

  </a>

</div>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Relatório de Aula Prática 01 - Teste</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Mostrar o código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Esconder o código</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Ver o código fonte</a></li></ul></div></div>
<p class="subtitle lead"><a href="https://bendeivide.github.io/courses/epaec/" target="_blank">Estatística e Probabilidade</a> <br> <a href="https://bendeivide.github.io" target="_blank">Prof.&nbsp;Ben Dêivide (DEFIM/CAP/UFSJ)</a></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Jair Malta e Wesley Pinheiro </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">20/08/2026, 23:15</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introdução" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução"><span class="header-section-number">1</span> 📌 Introdução</h2>
<p>A Estatística é uma área fundamental para a análise, interpretação e tomada de decisão com base em dados. No contexto das Engenharias e Ciências, essa área permite transformar informações brutas em resultados organizados, facilitando a compreensão de fenômenos, processos e problemas reais. Por meio da estatística, podemos tomar decisões sobre uma população através da amostra, importante pois poupa tempo e dinheiro.</p>
<p>Nesse primeiro momento, trataremos de Estatística Descritiva, apresentando conceitos como população, amostra, variável, dados, coleta, organização, tabelas de frequência, gráficos, medidas de posição, medidas de dispersão, assimetria e curtose. Esses conteúdos são essenciais para compreender como os dados podem ser tratados e resumidos antes da aplicação de técnicas estatísticas mais avançadas.</p>
<p>Além da estatística em sua essência, com o avanço das tecnologias a estatística manual e braçal cedeu espaço para softwares com grande capacidade de processamento de dados, como por exemplo o R Studio, que utiliza a linguagem de programação R em um ambiente computacional voltado principalmente para estatística, análise de dados e construção de gráficos. De forma simples, pode-se dizer que o R é a linguagem e o ambiente que executa os cálculos, enquanto o RStudio é a ferramenta que organiza e facilita o uso dessa linguagem. O RStudio permite escrever comandos, executar linhas de código, visualizar resultados, criar gráficos, consultar ajuda e gerenciar projetos.</p>
</section>
<section id="objetivos" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="objetivos"><span class="header-section-number">2</span> 🎯 Objetivos</h2>
<section id="objetivo-geral" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="objetivo-geral"><span class="header-section-number">2.1</span> Objetivo geral</h3>
<p>Resumir os principais conceitos apresentados nos quatro primeiros capítulos do livro Estatística &amp; Probabilidade aplicada às Engenharias e Ciências; introduzir conceitos iniciais da linguagem R e do RStudio, por exemplo Sintaxe e Semântica; realizar uma aplicação prática unindo os 2 temas anteriores.</p>
</section>
<section id="objetivos-específicos" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="objetivos-específicos"><span class="header-section-number">2.2</span> Objetivos específicos</h3>
<ul>
<li>Apresentar as definições iniciais da Estatística, incluindo população, amostra, variável e dado;</li>
<li>Explicar a importância da coleta, organização e apresentação dos dados;</li>
<li>Descrever as principais medidas de posição, como média, mediana e moda;</li>
<li>Apresentar as principais medidas de dispersão, como amplitude, variância, desvio padrão, coeficiente de variação e erro padrão da média;</li>
<li>Apresentar os conceitos de assimetria e curtose;</li>
<li>Explicar conceitos e ideias iniciais da linguagem R e do RStudio. Passos iniciais, aplicações e sua sintaxe e Semântica.</li>
<li>Relacionar todos os itens e conceitos acima e realizar uma aplicação prática mesclando a estatística descritiva com a linguagem R e RStudio.</li>
</ul>
</section>
</section>
<section id="metodologia" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metodologia"><span class="header-section-number">3</span> ⚙️ Metodologia</h2>
<div style="text-align: justify;">
<p>Este relatório foi elaborado a partir da leitura e análise dos quatro primeiros capítulos do livro digital Estatística &amp; Probabilidade aplicada às Engenharias e Ciências, da visualização e compreensão dos vídeos do Curso R Básico 2024 e conteúdos auxiliares como o R Studio, Pacote Leem e Rmarkdown. A metodologia utilizada consistiu em identificar os principais conceitos, definições e aplicações sintetizando as ideias centrais de forma objetiva e organizada. A estrutura do relatório foi organizada em introdução, objetivos, metodologia, resultados e discussão, conclusão e referências. O foco foi produzir um resumo claro, com linguagem acadêmica simples e adequada.</p>
<section id="resultados-e-discussão" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="resultados-e-discussão"><span class="header-section-number">4</span> 🔍 Resultados e Discussão</h2>
<section id="capítulo-1-definições-gerais-da-estatística-e-técnicas-de-somatórios" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="capítulo-1-definições-gerais-da-estatística-e-técnicas-de-somatórios"><span class="header-section-number">4.1</span> Capítulo 1: Definições Gerais da Estatística e técnicas de somatórios</h3>
<p>O primeiro capítulo apresenta a Estatística como uma ciência voltada à coleta, organização, descrição, análise e interpretação de dados. Segunda Batista (2024) na era digital há uma grande produção de informações, especialmente em ambientes como redes sociais, plataformas digitais e sistemas corporativos, sendo necessário utilizar métodos estatísticos para compreender esses dados e auxiliar na tomada de decisões.</p>
<p>O capítulo diferencia três grandes áreas da Estatística: Estatística Descritiva, Probabilidade e Estatística Inferencial. A Estatística Descritiva reúne técnicas de coleta, organização, tabulação, representação gráfica e cálculo de medidas que resumem os dados. A Probabilidade é apresentada como a teoria matemática voltada ao estudo da incerteza em fenômenos aleatórios. Já a Estatística Inferencial busca utilizar informações de uma amostra para tirar conclusões sobre uma população.</p>
<p>Também são introduzidos conceitos básicos como população, amostra, variável e dado. - População é o conjunto de elementos de interesse da pesquisa e amostra é um subconjunto dessa população; - Variável é a característica que se deseja estudar, sendo dividida em Qualitativa (Nomina e ordinal) e Quantitativa (Discreta e Contínua); - Dado é o valor observado dessa característica em cada elemento.</p>
<p>O capítulo ainda relaciona a Estatística ao método científico, destacando etapas como identificação do problema, formulação de hipóteses, revisão de literatura, coleta de dados, análise e apresentação dos resultados.</p>
</section>
<section id="capítulo-2-coleta-organização-e-apresentação-dos-dados" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="capítulo-2-coleta-organização-e-apresentação-dos-dados"><span class="header-section-number">4.2</span> Capítulo 2: Coleta, organização e apresentação dos dados</h3>
<p>O segundo capítulo trata da etapa posterior à definição da população e das variáveis de interesse: a coleta e organização dos dados. O autor explica que os dados coletados sem ordenação ou arranjo sistemático são chamados de dados brutos. Quando esses dados são organizados em ordem crescente ou decrescente, passam a ser chamados de dados em rol ou dados elaborados.</p>
<p>Um dos principais pontos do capítulo é a construção de tabelas de frequência. A frequência absoluta indica quantas vezes determinado valor aparece no conjunto de dados, enquanto a frequência relativa representa essa ocorrência em relação ao total de observações. A frequência percentual transforma a frequência relativa em porcentagem, facilitando a interpretação. O capítulo também apresenta frequências acumuladas, que permitem responder perguntas como “quantos valores estão abaixo de determinado ponto?” ou “quantos valores estão acima de determinado ponto?”.</p>
<p>O capítulo 2 apresenta como utilizar o pacote leem para tabular dados e também como instalar o pacote propriamente dito no RStudio.</p>
<p>Além das tabelas, o capítulo discute o agrupamento de variáveis quantitativas contínuas em intervalos de classe. Esse procedimento é importante quando há muitos dados ou quando os valores não são naturalmente discretos. O autor apresenta critérios para definir o número de classes, a amplitude total e a amplitude de cada classe, mostrando a importância da organização dos dados para facilitar sua leitura, interpretação e apresentação.</p>
<p>É apresentado também representações gráficas, ferramentas que facilitam a visualização mesmo em situações de complexidade, ajudando assim na análise e compreensão. São citados tipos de gráficos como gráfico de barras, histogramas, gráfico de linhas, gráfico de dispersão. É mencionado também, no ambiente R, o pacote “graphics” e o “ggplot2” que auxiliam no tratamento dos dados e criação dos gráficos no RStudio.</p>
</section>
<section id="capítulo-3-medidas-de-posição" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="capítulo-3-medidas-de-posição"><span class="header-section-number">4.3</span> Capítulo 3: Medidas de Posição</h3>
<p>O terceiro capítulo apresenta as medidas de posição, também chamadas de medidas de tendência central. Essas medidas são utilizadas para resumir um conjunto de dados por meio de valores representativos, indicando em torno de qual ponto os dados se concentram. As principais medidas estudadas são a média aritmética, a mediana e a moda.</p>
<p>A média aritmética, populacional (Equação 1) e amostral (Equação 2) é apresentada como uma das medidas mais conhecidas e utilizadas. Ela representa um ponto de equilíbrio dos dados e pode ser calculada tanto para dados não agrupados quanto para dados agrupados. No entanto, o capítulo destaca que a média é sensível a valores discrepantes, ou seja, valores muito distantes da maioria das observações podem alterar significativamente seu resultado. Para esses casos sugere-se a utilização da média aparada(Equação 3), onde é excluído do cálculo o valor mínimo e máximo de um conjunto de dados.</p>
<p><span class="math display">\[
\mu = \frac{1}{N}\sum_{i=1}^{N} x_i \tag{1}
\]</span></p>
<p><span class="math display">\[
\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i \tag{2}
\]</span> <span class="math display">\[
\bar{x}_{trim} =
\frac{1}{n - 2k}
\sum_{i=k+1}^{n-k} x_{(i)} \tag{3}
\]</span> A mediana é definida como o valor central de um conjunto de dados ordenado (Equações 4 e 5). Ela divide o conjunto em duas partes, de modo que aproximadamente 50% dos valores fiquem abaixo e 50% fiquem acima. Por considerar a posição dos dados e não diretamente seus valores extremos, a mediana é menos influenciada por dados discrepantes/extremos. Quando há dados agrupados em intervalos de classes o cálculo utiliza outros parâmetros, como limite inferior e superior da classe, frequência acumulada da classe anterior à classe em questão e frequência absoluta da classe mediana.</p>
<p><span class="math display">\[
\begin{equation}
\text{Mediana} =
\begin{cases}
x_{(\frac{N+1}{2})}, &amp; \text{se } N \text{ ímpar} \\
\frac{x_{(\frac{N}{2})} + x_{(\frac{N}{2}+1})}{2}, &amp; \text{se } N \text{ par}
\end{cases}
\tag{4}
\end{equation}
\]</span> <span class="math display">\[
\begin{equation}
\tilde{x} =
\begin{cases}
x_{(\frac{n+1}{2})}, &amp; \text{se } n \text{ ímpar} \\
\frac{x_{(\frac{n}{2})} + x_{(\frac{n}{2}+1})}{2}, &amp; \text{se } n \text{ par}
\end{cases}
\tag{5}
\end{equation}
\]</span> A moda, por sua vez, representa o valor mais frequente em um conjunto de dados e pode ser aplicada a diferentes tipos de variáveis, inclusive qualitativas. Vale destacar que, um conjunto de dados poderá ter mais de uma moda, isto é, se observarmos dois valores mais frequentes e iguais, teremos uma distribuição bimodal. Da mesma forma que a mediana, a moda não é influenciada por valores extremos, desde que estes não pertençam a classe modal.</p>
<p>O capítulo também mostra que média, mediana e moda podem oferecer interpretações diferentes de um mesmo conjunto de dados. Em distribuições mais simétricas, essas medidas tendem a se aproximar. Em distribuições assimétricas ou com valores extremos, elas podem apresentar diferenças importantes, sendo necessário escolher a medida mais adequada conforme a natureza dos dados e o objetivo da análise.</p>
<p>Por fim é apresentado como o Pacote leem pode contribuir para o cálculo rápido das medidas média, mediana e moda utilizando as funções mean(), median() e mfreq(), respectivamente.</p>
</section>
<section id="capítulo-4-medidas-de-dispersão" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="capítulo-4-medidas-de-dispersão"><span class="header-section-number">4.4</span> Capítulo 4: Medidas de dispersão</h3>
<p>O quarto capítulo complementa o estudo das medidas de posição ao apresentar as medidas de dispersão. É apresentado que conjuntos de dados diferentes podem possuir a mesma média, mas apresentar comportamentos distintos. Isso demonstra que apenas uma medida central não é suficiente para caracterizar adequadamente os dados.</p>
<p>A primeira medida apresentada é a amplitude, definida como a diferença entre o maior e o menor valor do conjunto. Embora seja simples de calcular e esteja na mesma unidade da variável, a amplitude possui limitações, pois considera apenas os valores extremos e ignora o comportamento dos demais dados. Por isso, a amplitude pode não representar adequadamente a variabilidade total de um conjunto.</p>
<p>Em seguida, o capítulo apresenta a variância, que mede a dispersão dos dados em relação à média por meio dos desvios ao quadrado. A variância considera todos os valores do conjunto, sendo uma medida mais completa do que a amplitude. Entretanto, sua unidade fica elevada ao quadrado, o que pode dificultar a interpretação prática. Por esse motivo, utiliza-se também o desvio padrão, que corresponde à raiz quadrada da variância e retorna a medida de dispersão para a mesma unidade da variável analisada.</p>
<p>É importante saber que quanto mais próximo de zero a variância e o desvio padrão for, mais concentrado e melhor representado os dados estão com relação à média. Além disso, para utilizar variância e desvio padrão para comparar grupos de dados, temos que verificar se a média desses grupos são iguais e se as observações estão na mesma unidade de mensuração.</p>
<p>O capítulo também aborda o coeficiente de variação, uma medida relativa de dispersão que expressa o desvio padrão em relação à média, geralmente em porcentagem. Essa medida permite comparar a variabilidade entre grupos diferentes, desde que a variável analisada possua uma escala adequada. Por fim, o autor apresenta o erro padrão da média, que está relacionado à precisão com que a média amostral estima a média populacional e será importante em conteúdos posteriores, como estimação e testes de hipóteses.</p>
</section>
<section id="assimetria-e-curtose" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="assimetria-e-curtose"><span class="header-section-number">4.5</span> Assimetria e curtose</h3>
<p>Além das medidas de posição e dispersão, a análise estatística também pode considerar medidas relacionadas ao formato da distribuição dos dados, como a assimetria e a curtose. Essas medidas ajudam a compreender não apenas onde os dados se concentram e o quanto variam, mas também como os valores estão distribuídos ao redor da média. A assimetria indica o grau de afastamento de uma distribuição em relação à simetria, ou seja, descreve o equilíbrio da distribuição. A curtose ajuda a avaliar o peso das caudas e a ocorrência de valores extremos.</p>
<p>Uma distribuição é considerada aproximadamente simétrica quando os dados se distribuem de forma semelhante dos dois lados de uma medida central. Nesse caso, média, mediana e moda tendem a apresentar valores próximos. Quando a distribuição possui uma cauda mais alongada para a direita, ocorre assimetria positiva. Nesse tipo de situação, alguns valores altos podem puxar a média para cima. Quando a cauda é mais alongada para a esquerda, ocorre assimetria negativa, indicando a presença de valores baixos que influenciam a distribuição.</p>
<p>A análise da assimetria é importante porque permite avaliar se a média representa bem o conjunto de dados. Em distribuições muito assimétricas, a média pode ser fortemente afetada por valores extremos, sendo recomendável observar também a mediana e a moda. Dessa forma, a assimetria se relaciona diretamente ao conteúdo do Capítulo 3 do livro, no qual são discutidas as medidas de posição e suas diferentes interpretações.</p>
<p>A curtose está relacionada ao grau de concentração dos dados em torno do centro da distribuição e ao peso das caudas. De forma geral, a curtose ajuda a identificar se uma distribuição apresenta maior concentração de valores próximos à média ou maior ocorrência de valores extremos. Uma distribuição com curtose mais elevada tende a indicar maior presença de valores extremos ou caudas mais pesadas. Já uma curtose menor indica uma distribuição mais achatada, com menor concentração central ou caudas menos intensas.</p>
<p>Em suma, assimetria e curtose complementam as medidas de dispersão estudadas no Capítulo 4. Enquanto a variância, o desvio padrão e o coeficiente de variação indicam o nível de variabilidade, a assimetria e a curtose ajudam a interpretar o formato da distribuição e a presença de valores extremos.</p>
</section>
<section id="introdução-básica-ao-r-linguagem-e-software" class="level3" data-number="4.6">
<h3 data-number="4.6" class="anchored" data-anchor-id="introdução-básica-ao-r-linguagem-e-software"><span class="header-section-number">4.6</span> Introdução básica ao R (linguagem e software)</h3>
<p>O R é uma linguagem de programação e um ambiente computacional voltado principalmente para estatística, análise de dados e construção de gráficos. O projeto R apresenta o software como um ambiente gratuito para computação estatística e gráficos, disponível para diferentes sistemas operacionais.</p>
<p>Para utilizar o R, é necessário instalar inicialmente o programa R, que executa os comandos estatísticos. A instalação pode ser feita pelo site oficial do projeto R, por meio da rede CRAN. Após instalar o R, recomenda-se instalar também o RStudio, que é uma interface de desenvolvimento integrada. O RStudio facilita o uso do R, pois reúne editor de código, console, gráficos, ambiente de trabalho, arquivos, pacotes e ajuda integrada em uma única interface.</p>
<p>De forma simples, pode-se dizer que o R é a linguagem e o ambiente que executa os cálculos, enquanto o RStudio é a ferramenta que organiza e facilita o uso dessa linguagem. O RStudio permite escrever comandos, executar linhas de código, visualizar resultados, criar gráficos, consultar ajuda e gerenciar projetos, além de possuir pacotes com integração à internet, por exemplo o HTML, para criação de relatórios, apresentações e outros diversos itens. Sua interface é dividida em 4 quadrantes sendo:</p>
<ul>
<li>1º Quadrante – Script do R - Área utilizada para escrever, editar e salvar os códigos em arquivos com extensão .R;</li>
<li>2º Quadrante – Console do R - Local onde os comandos são efetivamente executados e os resultados aparecem. Também permite digitar comandos diretamente, porém esses comandos não ficam organizados em um script, a menos que sejam salvos separadamente;</li>
<li>3º Quadrante – Ambiente Global - Exibe os objetos criados durante a análise, como vetores, tabelas, conjuntos de dados, funções e resultados de cálculos. Também apresenta o histórico dos comandos executados e permite acompanhar os dados armazenados na sessão atual;</li>
<li>4º Quadrante – Área de plotagem - Utilizado para visualizar gráficos, consultar arquivos e pastas, gerenciar pacotes e acessar a documentação de ajuda das funções.</li>
</ul>
</section>
<section id="sintaxe-e-semântica-do-r" class="level3" data-number="4.7">
<h3 data-number="4.7" class="anchored" data-anchor-id="sintaxe-e-semântica-do-r"><span class="header-section-number">4.7</span> Sintaxe e semântica do R</h3>
<p>A linguagem R, assim como outras linguagens de programação, possui sintaxe e semântica. A sintaxe está relacionada à forma correta de escrever os comandos. Em outras palavras, a sintaxe define as regras de escrita que o R reconhece. Se um comando for escrito de forma incorreta, o programa poderá apresentar erro.</p>
<p>Por exemplo, para criar um conjunto de dados no R, pode-se usar o comando:</p>
<ul>
<li>dados &lt;- c (3, 1, 0, 1, 3, 2, 4, 1, 3, 1)</li>
</ul>
<p>Nesse exemplo, dados é o nome do objeto criado, &lt;- é o operador de atribuição, e c() é uma função usada para combinar valores em um vetor. A escrita correta dos parênteses, vírgulas e símbolos faz parte da sintaxe da linguagem.</p>
<p>A semântica, por outro lado, diz respeito ao significado dos comandos. Ou seja, enquanto a sintaxe trata da forma correta de escrever, a semântica trata do que aquele comando representa ou executa. No exemplo anterior, o significado do comando é armazenar uma sequência de valores numéricos dentro de um objeto chamado dados.</p>
<p>Após criar esse objeto, é possível aplicar funções estatísticas: - mean(dados) # calcula a média - median(dados) # calcula a mediana - var(dados) # calcula a variância - sd(dados) # calcula o desvio padrão</p>
<p>A sintaxe desses comandos envolve o nome da função, como mean, median, var e sd, seguido dos parênteses com o objeto analisado. Já a semântica está no significado de cada função. A função mean() calcula a média aritmética, median() calcula a mediana, var() calcula a variância e sd() calcula o desvio padrão.</p>
<p>Outro ponto importante da sintaxe do R é que a linguagem diferencia letras maiúsculas de minúsculas. Assim, um objeto chamado dados é diferente de outro chamado Dados. Também é comum usar comentários no código, iniciados pelo símbolo #. Os comentários não são executados pelo R, servindo apenas para explicar o código.</p>
<p>Portanto, compreender sintaxe e semântica é essencial para utilizar o R corretamente. A sintaxe permite escrever comandos sem erros, enquanto a semântica permite entender o significado das operações realizadas. Esse conhecimento é importante para aplicar os conceitos estatísticos estudados, como organização de dados, medidas de posição, medidas de dispersão, assimetria e curtose.</p>
</section>
</section>
<section id="estudo-de-caso-e-aplicação" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="estudo-de-caso-e-aplicação"><span class="header-section-number">5</span> Estudo de Caso e Aplicação</h2>
<section id="contexto-do-projeto" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="contexto-do-projeto"><span class="header-section-number">5.1</span> Contexto do Projeto</h3>
<p>A obra em questão consiste na execução de um muro de arrimo em concreto armado, com função estrutural de contenção de um talude de mineração (cava de extração de minério de ferro). O muro possui altura média de 12 m, extensão linear de 180 m e volume total estimado de concreto de 2.400 m³.</p>
<p>A resistência característica à compressão (fck) de projeto especificada no memorial de cálculo é de 30 MPa (30.000 kPa), para que o elemento suporte os empuxos de terra, sobrecargas de equipamentos e ações hidrostáticas.</p>
<p>O concreto foi dosado em usina própria da mineradora, com traço 1:2,5:3,0 (cimento:areia: brita), relação a/c = 0,48 e adição de superplastificante à base de policarboxilato para garantir trabalhabilidade (slump de 120 ± 20 mm) mesmo com alta densidade de armadura.</p>
</section>
<section id="plano-de-amostragem-e-produção" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="plano-de-amostragem-e-produção"><span class="header-section-number">5.2</span> Plano de Amostragem e Produção</h3>
<p>A concretagem do muro foi dividida em 3 dias consecutivos de produção, denominados Grupo A, B e C, correspondentes a:</p>
<ul>
<li>Grupo A (Dia 1 – 08/08/2026): concretagem da base e primeira elevação (1/3 do muro) – 17 corpos de prova.</li>
<li>Grupo B (Dia 2 – 09/08/2026): concretagem da segunda elevação (trecho central) – 18 corpos de prova.</li>
<li>Grupo C (Dia 3 – 10/08/2026): concretagem da coroa e fechamento superior – 15 corpos de prova.</li>
</ul>
<p>Cada dia de produção correspondeu a um caminhão betoneira diferente (mesmo traço, mas com pequenas variações inerentes à umidade dos agregados e ao tempo de mistura), o que justifica a separação em grupos para fins de rastreabilidade.</p>
</section>
<section id="coleta-e-preparação-dos-corpos-de-prova" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="coleta-e-preparação-dos-corpos-de-prova"><span class="header-section-number">5.3</span> Coleta e Preparação dos Corpos de Prova</h3>
<p>Em cada dia de concretagem, foram moldados corpos de prova cilíndricos (dimensões: 10 cm × 20 cm), conforme prescrições da NBR 5738. A amostragem foi feita no ponto de descarga do caminhão betoneira, imediatamente antes do lançamento no muro, seguindo o critério de 1 corpo de prova a cada 50 m³ de concreto lançado (excedendo o mínimo normativo para garantir robustez estatística).</p>
<p>Os corpos de prova foram:</p>
<ul>
<li>Desmoldados após 24 horas;</li>
<li>Cura úmida em câmara úmida (temperatura 23 ± 2 °C e umidade relativa ≥ 95%) por 7 dias;</li>
<li>Mantidos em condição ambiente do laboratório até a data do ensaio (aos 28 dias).</li>
</ul>
<p>Os resultados obtidos podem ser observados na</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>corposdeprova <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/Users/Dell/Desktop/relatórios/relatorio-eait/relatorio/rel01/corposdeprova.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Número de colunas (para aplicar centralização em todas)</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>n_col <span class="ot">&lt;-</span> <span class="fu">ncol</span>(corposdeprova)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(corposdeprova, </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Dados dos Corpos de Prova"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">align =</span> <span class="fu">rep</span>(<span class="st">"c"</span>, n_col)) <span class="sc">%&gt;%</span>  <span class="co"># garante todas as colunas centralizadas</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">position =</span> <span class="st">"center"</span>) <span class="sc">%&gt;%</span>  <span class="co"># centraliza a tabela na página</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span><span class="sc">:</span>n_col, <span class="at">extra_css =</span> <span class="st">"text-align: center;"</span>) <span class="sc">%&gt;%</span>  <span class="co"># força centralização</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scroll_box</span>(<span class="at">width =</span> <span class="st">"100%"</span>, <span class="at">height =</span> <span class="st">"400px"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:400px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Dados dos Corpos de Prova</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">Grupo</th>
<th data-quarto-table-cell-role="th" style="text-align: center; position: sticky; top: 0; background-color: #FFFFFF;">Resistencia_kPa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">27850</td>
</tr>
<tr class="even">
<td style="text-align: center;">A</td>
<td style="text-align: center;">26430</td>
</tr>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">29120</td>
</tr>
<tr class="even">
<td style="text-align: center;">A</td>
<td style="text-align: center;">28560</td>
</tr>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">25970</td>
</tr>
<tr class="even">
<td style="text-align: center;">A</td>
<td style="text-align: center;">30210</td>
</tr>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">27340</td>
</tr>
<tr class="even">
<td style="text-align: center;">A</td>
<td style="text-align: center;">26880</td>
</tr>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">28900</td>
</tr>
<tr class="even">
<td style="text-align: center;">A</td>
<td style="text-align: center;">29670</td>
</tr>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">27110</td>
</tr>
<tr class="even">
<td style="text-align: center;">A</td>
<td style="text-align: center;">28440</td>
</tr>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">26050</td>
</tr>
<tr class="even">
<td style="text-align: center;">A</td>
<td style="text-align: center;">30550</td>
</tr>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">29830</td>
</tr>
<tr class="even">
<td style="text-align: center;">A</td>
<td style="text-align: center;">27720</td>
</tr>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">28190</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">31450</td>
</tr>
<tr class="odd">
<td style="text-align: center;">B</td>
<td style="text-align: center;">30870</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">33220</td>
</tr>
<tr class="odd">
<td style="text-align: center;">B</td>
<td style="text-align: center;">29560</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">34100</td>
</tr>
<tr class="odd">
<td style="text-align: center;">B</td>
<td style="text-align: center;">32680</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">30990</td>
</tr>
<tr class="odd">
<td style="text-align: center;">B</td>
<td style="text-align: center;">33550</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">31240</td>
</tr>
<tr class="odd">
<td style="text-align: center;">B</td>
<td style="text-align: center;">35670</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">29880</td>
</tr>
<tr class="odd">
<td style="text-align: center;">B</td>
<td style="text-align: center;">32410</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">34230</td>
</tr>
<tr class="odd">
<td style="text-align: center;">B</td>
<td style="text-align: center;">30120</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">33890</td>
</tr>
<tr class="odd">
<td style="text-align: center;">B</td>
<td style="text-align: center;">31760</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">36050</td>
</tr>
<tr class="odd">
<td style="text-align: center;">B</td>
<td style="text-align: center;">32540</td>
</tr>
<tr class="even">
<td style="text-align: center;">C</td>
<td style="text-align: center;">38220</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">39670</td>
</tr>
<tr class="even">
<td style="text-align: center;">C</td>
<td style="text-align: center;">37450</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">40110</td>
</tr>
<tr class="even">
<td style="text-align: center;">C</td>
<td style="text-align: center;">36890</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">41230</td>
</tr>
<tr class="even">
<td style="text-align: center;">C</td>
<td style="text-align: center;">38540</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">39980</td>
</tr>
<tr class="even">
<td style="text-align: center;">C</td>
<td style="text-align: center;">37120</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">40670</td>
</tr>
<tr class="even">
<td style="text-align: center;">C</td>
<td style="text-align: center;">42300</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">38770</td>
</tr>
<tr class="even">
<td style="text-align: center;">C</td>
<td style="text-align: center;">41890</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">39450</td>
</tr>
<tr class="even">
<td style="text-align: center;">C</td>
<td style="text-align: center;">40020</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leem)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Carregar dados</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>corposdeprova <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/Users/Dell/Desktop/relatórios/relatorio-eait/relatorio/rel01/corposdeprova.csv"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ==================== GRUPO A ====================</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>dados_A <span class="ot">&lt;-</span> corposdeprova<span class="sc">$</span>Resistencia_kPa[corposdeprova<span class="sc">$</span>Grupo <span class="sc">==</span> <span class="st">"A"</span>]</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Média (kPa → MPa)</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>media_A_MPa <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados_A) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>media_A_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(media_A_MPa, <span class="dv">2</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Mediana (kPa → MPa)</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>mediana_A_MPa <span class="ot">&lt;-</span> <span class="fu">median</span>(dados_A) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>mediana_A_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(mediana_A_MPa, <span class="dv">2</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Desvio Padrão (kPa → MPa)</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>desvio_A <span class="ot">&lt;-</span> <span class="fu">sd</span>(dados_A) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>desvio_A_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(desvio_A, <span class="dv">2</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Variância (kPa² → MPa²)</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>variancia_A <span class="ot">&lt;-</span> <span class="fu">var</span>(dados_A) <span class="sc">/</span> (<span class="dv">1000</span><span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>variancia_A_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(variancia_A, <span class="dv">2</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficiente de Variação (mesmo em %)</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>cv_A <span class="ot">&lt;-</span> (<span class="fu">sd</span>(dados_A) <span class="sc">/</span> <span class="fu">mean</span>(dados_A)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>cv_A_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(cv_A, <span class="dv">2</span>)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Assimetria (adimensional)</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(dados_A)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_A <span class="sc">-</span> <span class="fu">mean</span>(dados_A))<span class="sc">^</span><span class="dv">3</span>) <span class="sc">/</span> n</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>s3 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_A <span class="sc">-</span> <span class="fu">mean</span>(dados_A))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span>(<span class="dv">3</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>assimetria_A <span class="ot">&lt;-</span> m3 <span class="sc">/</span> s3</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>assimetria_A_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(assimetria_A, <span class="dv">3</span>)</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Curtose (adimensional)</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_A <span class="sc">-</span> <span class="fu">mean</span>(dados_A))<span class="sc">^</span><span class="dv">4</span>) <span class="sc">/</span> n</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>s4 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_A <span class="sc">-</span> <span class="fu">mean</span>(dados_A))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>curtose_A <span class="ot">&lt;-</span> m4 <span class="sc">/</span> s4</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>curtose_A_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(curtose_A, <span class="dv">3</span>)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Mínimo (kPa → MPa)</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>min_A <span class="ot">&lt;-</span> <span class="fu">min</span>(dados_A) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>min_A_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(min_A, <span class="dv">2</span>)</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Máximo (kPa → MPa)</span></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>max_A <span class="ot">&lt;-</span> <span class="fu">max</span>(dados_A) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>max_A_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(max_A, <span class="dv">2</span>)</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Amplitude Total (kPa → MPa)</span></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>amplitude_A <span class="ot">&lt;-</span> (<span class="fu">max</span>(dados_A) <span class="sc">-</span> <span class="fu">min</span>(dados_A)) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>amplitude_A_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(amplitude_A, <span class="dv">2</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ==================== GRUPO B ====================</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dados_B <span class="ot">&lt;-</span> corposdeprova<span class="sc">$</span>Resistencia_kPa[corposdeprova<span class="sc">$</span>Grupo <span class="sc">==</span> <span class="st">"B"</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Média (kPa → MPa)</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>media_B_MPa <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados_B) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>media_B_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(media_B_MPa, <span class="dv">2</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Mediana (kPa → MPa)</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>mediana_B_MPa <span class="ot">&lt;-</span> <span class="fu">median</span>(dados_B) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>mediana_B_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(mediana_B_MPa, <span class="dv">2</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Desvio Padrão (kPa → MPa)</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>desvio_B <span class="ot">&lt;-</span> <span class="fu">sd</span>(dados_B) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>desvio_B_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(desvio_B, <span class="dv">2</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Variância (kPa² → MPa²)</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>variancia_B <span class="ot">&lt;-</span> <span class="fu">var</span>(dados_B) <span class="sc">/</span> (<span class="dv">1000</span><span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>variancia_B_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(variancia_B, <span class="dv">2</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficiente de Variação (mesmo em %)</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>cv_B <span class="ot">&lt;-</span> (<span class="fu">sd</span>(dados_B) <span class="sc">/</span> <span class="fu">mean</span>(dados_B)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>cv_B_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(cv_B, <span class="dv">2</span>)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Assimetria (adimensional)</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(dados_B)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_B <span class="sc">-</span> <span class="fu">mean</span>(dados_B))<span class="sc">^</span><span class="dv">3</span>) <span class="sc">/</span> n</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>s3 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_B <span class="sc">-</span> <span class="fu">mean</span>(dados_B))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span>(<span class="dv">3</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>assimetria_B <span class="ot">&lt;-</span> m3 <span class="sc">/</span> s3</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>assimetria_B_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(assimetria_B, <span class="dv">3</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Curtose (adimensional)</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_B <span class="sc">-</span> <span class="fu">mean</span>(dados_B))<span class="sc">^</span><span class="dv">4</span>) <span class="sc">/</span> n</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>s4 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_B <span class="sc">-</span> <span class="fu">mean</span>(dados_B))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>curtose_B <span class="ot">&lt;-</span> m4 <span class="sc">/</span> s4</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>curtose_B_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(curtose_B, <span class="dv">3</span>)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Mínimo (kPa → MPa)</span></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>min_B <span class="ot">&lt;-</span> <span class="fu">min</span>(dados_B) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>min_B_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(min_B, <span class="dv">2</span>)</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Máximo (kPa → MPa)</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>max_B <span class="ot">&lt;-</span> <span class="fu">max</span>(dados_B) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>max_B_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(max_B, <span class="dv">2</span>)</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Amplitude Total (kPa → MPa)</span></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>amplitude_B <span class="ot">&lt;-</span> (<span class="fu">max</span>(dados_B) <span class="sc">-</span> <span class="fu">min</span>(dados_B)) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>amplitude_B_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(amplitude_B, <span class="dv">2</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ==================== GRUPO C ====================</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dados_C <span class="ot">&lt;-</span> corposdeprova<span class="sc">$</span>Resistencia_kPa[corposdeprova<span class="sc">$</span>Grupo <span class="sc">==</span> <span class="st">"C"</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Média (kPa → MPa)</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>media_C_MPa <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados_C) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>media_C_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(media_C_MPa, <span class="dv">2</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Mediana (kPa → MPa)</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>mediana_C_MPa <span class="ot">&lt;-</span> <span class="fu">median</span>(dados_C) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>mediana_C_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(mediana_C_MPa, <span class="dv">2</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Desvio Padrão (kPa → MPa)</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>desvio_C <span class="ot">&lt;-</span> <span class="fu">sd</span>(dados_C) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>desvio_C_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(desvio_C, <span class="dv">2</span>)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Variância (kPa² → MPa²)</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>variancia_C <span class="ot">&lt;-</span> <span class="fu">var</span>(dados_C) <span class="sc">/</span> (<span class="dv">1000</span><span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>variancia_C_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(variancia_C, <span class="dv">2</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficiente de Variação (mesmo em %)</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>cv_C <span class="ot">&lt;-</span> (<span class="fu">sd</span>(dados_C) <span class="sc">/</span> <span class="fu">mean</span>(dados_C)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>cv_C_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(cv_C, <span class="dv">2</span>)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Assimetria (adimensional)</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(dados_C)</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_C <span class="sc">-</span> <span class="fu">mean</span>(dados_C))<span class="sc">^</span><span class="dv">3</span>) <span class="sc">/</span> n</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>s3 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_C <span class="sc">-</span> <span class="fu">mean</span>(dados_C))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span>(<span class="dv">3</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>assimetria_C <span class="ot">&lt;-</span> m3 <span class="sc">/</span> s3</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>assimetria_C_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(assimetria_C, <span class="dv">3</span>)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Curtose (adimensional)</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_C <span class="sc">-</span> <span class="fu">mean</span>(dados_C))<span class="sc">^</span><span class="dv">4</span>) <span class="sc">/</span> n</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>s4 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_C <span class="sc">-</span> <span class="fu">mean</span>(dados_C))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>curtose_C <span class="ot">&lt;-</span> m4 <span class="sc">/</span> s4</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>curtose_C_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(curtose_C, <span class="dv">3</span>)</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Mínimo (kPa → MPa)</span></span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>min_C <span class="ot">&lt;-</span> <span class="fu">min</span>(dados_C) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>min_C_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(min_C, <span class="dv">2</span>)</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Máximo (kPa → MPa)</span></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>max_C <span class="ot">&lt;-</span> <span class="fu">max</span>(dados_C) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>max_C_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(max_C, <span class="dv">2</span>)</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Amplitude Total (kPa → MPa)</span></span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>amplitude_C <span class="ot">&lt;-</span> (<span class="fu">max</span>(dados_C) <span class="sc">-</span> <span class="fu">min</span>(dados_C)) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>amplitude_C_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(amplitude_C, <span class="dv">2</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="análise-prática-de-cada-grupo" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="análise-prática-de-cada-grupo"><span class="header-section-number">5.4</span> Análise prática de cada grupo</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Estatística</th>
<th>Grupo A</th>
<th>Grupo B</th>
<th>Grupo C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Média (MPa)</td>
<td>28.17</td>
<td>32.46</td>
<td>39.49</td>
</tr>
<tr class="even">
<td>Mediana (MPa)</td>
<td>28.19</td>
<td>32.48</td>
<td>39.67</td>
</tr>
<tr class="odd">
<td>Desvio Padrão (MPa)</td>
<td>1.43</td>
<td>1.9</td>
<td>1.66</td>
</tr>
<tr class="even">
<td>Variância (MPa²)</td>
<td>2.04</td>
<td>3.59</td>
<td>2.76</td>
</tr>
<tr class="odd">
<td>CV (%)</td>
<td>5.07</td>
<td>5.84</td>
<td>4.2</td>
</tr>
<tr class="even">
<td>Assimetria</td>
<td>0.048</td>
<td>0.266</td>
<td>0.018</td>
</tr>
<tr class="odd">
<td>Curtose</td>
<td>1.924</td>
<td>2.194</td>
<td>2.067</td>
</tr>
<tr class="even">
<td>Mínimo (MPa)</td>
<td>25.97</td>
<td>29.56</td>
<td>36.89</td>
</tr>
<tr class="odd">
<td>Máximo (MPa)</td>
<td>30.55</td>
<td>36.05</td>
<td>42.3</td>
</tr>
<tr class="even">
<td>Amplitude (MPa)</td>
<td>4.58</td>
<td>6.49</td>
<td>5.41</td>
</tr>
</tbody>
</table>
<section id="grupo-a" class="level4" data-number="5.4.1">
<h4 data-number="5.4.1" class="anchored" data-anchor-id="grupo-a"><span class="header-section-number">5.4.1</span> Grupo A</h4>
<p>O grupo A apresentou resistência média de 28.17 MPa e mediana de 28.19 MPa. A proximidade entre essas duas medidas é um primeiro indício de que a distribuição é equilibrada e não está sendo fortemente afetada por valores extremos.</p>
<p>O coeficiente de assimetria foi:</p>
<p>0.048</p>
<p>Como o resultado está muito próximo de zero, a distribuição do grupo A pode ser considerada aproximadamente simétrica. O pequeno sinal positivo indica uma tendência mínima de alongamento à direita, mas a magnitude é tão baixa que não possui relevância prática nesse conjunto.</p>
<p>O desvio padrão foi de 1.43, indicando o afastamento típico dos resultados em torno da média. A amplitude foi de 4.58 MPa, correspondente à diferença entre o maior resultado, 30.55 MPa, e o menor, 25.97 MPa.</p>
<p>O coeficiente de variação foi:</p>
<p>5.07 %</p>
<p>Isso significa que o desvio padrão corresponde a aproximadamente 5.07 % O grupo apresenta, portanto, uma variabilidade relativamente pequena em comparação com seu nível médio de resistência.</p>
<p>O excesso de curtose foi de 1.924 O resultado negativo sugere que, nessa amostra, os valores se apresentam de forma relativamente mais distribuída e com caudas mais leves do que a distribuição normal. Não foram identificados valores atípicos pelo critério do intervalo interquartil.</p>
<p>Em suma, o grupo A apresentou resistência média de 28.17, baixa variabilidade relativa, distribuição aproximadamente simétrica e ausência de indícios estatísticos de valores discrepantes. A média e a mediana são praticamente iguais, indicando que ambas representam adequadamente o centro dos resultados.</p>
</section>
<section id="grupo-b" class="level4" data-number="5.4.2">
<h4 data-number="5.4.2" class="anchored" data-anchor-id="grupo-b"><span class="header-section-number">5.4.2</span> Grupo B</h4>
<p>O grupo B apresentou resistência média de 32.46 MPa e mediana de 32.48 MPa. Novamente, observa-se grande proximidade entre as duas medidas, indicando que a média não está sendo fortemente deslocada por valores extremos.</p>
<p>O coeficiente de assimetria foi:</p>
<p>0.266</p>
<p>O sinal positivo indica uma leve tendência de cauda à direita, causada pelos resultados mais elevados, como 35,670 MPa e 36,050 MPa. Entretanto, o valor de 0.266 ainda é relativamente próximo de zero. Portanto, a assimetria pode ser considerada pequena.</p>
<p>O grupo B apresentou o maior desvio padrão entre os três grupos:</p>
<p>1.9 MPa</p>
<p>Também apresentou a maior amplitude:</p>
<p>A=36.05 - 29.56=6,490 MPa</p>
<p>Esses resultados indicam que o grupo B possui maior dispersão absoluta. O coeficiente de variação foi de 5.84 %, também o maior entre os três grupos. Embora a diferença não seja muito elevada, o grupo B é relativamente o menos homogêneo.</p>
<p>O excesso de curtose foi de2.194, indicando uma distribuição relativamente achatada e sem forte concentração de resultados extremos. Pelo critério do intervalo interquartil, também não foram identificados valores atípicos.</p>
<p>Em suma, o grupo B apresentou resistência média de 32.46 MPa e leve assimetria positiva. Embora não tenham sido identificados valores discrepantes, o grupo apresentou a maior amplitude, o maior desvio padrão e o maior coeficiente de variação, sendo o grupo com maior variabilidade entre os corpos de prova.</p>
</section>
<section id="grupo-c" class="level4" data-number="5.4.3">
<h4 data-number="5.4.3" class="anchored" data-anchor-id="grupo-c"><span class="header-section-number">5.4.3</span> Grupo C</h4>
<p>O grupo C apresentou a maior resistência média:</p>
<p>39.49 MPa</p>
<p>Sua mediana foi de 39.67 MPa, novamente muito próxima da média. Essa proximidade indica que a distribuição é equilibrada e que os valores altos ou baixos não estão deslocando significativamente a média. O coeficiente de assimetria foi:</p>
<p>0.018</p>
<p>O valor está praticamente igual a zero, indicando uma distribuição aproximadamente simétrica. Portanto, tanto a média quanto a mediana representam adequadamente o centro dos resultados do grupo C.</p>
<p>O desvio padrão foi de 1.66 MPa, valor intermediário entre os grupos A e B. A amplitude foi:</p>
<p>A=42.3-36.89=5,410” MPa”</p>
<p>Entretanto, para comparar a homogeneidade dos grupos, o coeficiente de variação é mais informativo do que o desvio padrão isolado, porque leva em consideração a média de cada grupo. Para o grupo C:</p>
<p>**CV=4.2 %</p>
<p>Esse foi o menor coeficiente de variação entre os três grupos. Assim, apesar de o desvio padrão do grupo C ser maior que o do grupo A, sua dispersão é menor quando comparada proporcionalmente à respectiva média.</p>
<p>O excesso de curtose foi de 2.067, apontando uma distribuição relativamente mais achatada e sem caudas pesadas. Não foram identificados valores atípicos pelo critério do intervalo interquartil.</p>
<p>Em suma, o grupo C apresentou a maior resistência média e o menor coeficiente de variação. Os dados possuem distribuição aproximadamente simétrica, sem evidência de valores discrepantes. Em termos relativos, o grupo C apresentou a maior homogeneidade entre os corpos de prova.</p>
</section>
<section id="comparação-prática-dos-grupos" class="level4" data-number="5.4.4">
<h4 data-number="5.4.4" class="anchored" data-anchor-id="comparação-prática-dos-grupos"><span class="header-section-number">5.4.4</span> Comparação prática dos grupos</h4>
<p>A ordem das resistências médias foi:</p>
<p>“Grupo C”&gt;“Grupo B”&gt;“Grupo A”</p>
<p>As diferenças entre as médias foram:</p>
<ul>
<li>Grupo B em relação ao A: <strong>4,290 MPa, aproximadamente 15,23% superior;</strong></li>
<li>Grupo C em relação ao A: <strong>11,321 MPa, aproximadamente 40,20% superior;</strong></li>
<li>Grupo C em relação ao B: <strong>7,031 MPa, aproximadamente 21,66% superior.</strong></li>
</ul>
<p>Portanto, se os três grupos representam diferentes traços, materiais, idades de cura ou condições de fabricação, o grupo C apresentou o melhor resultado médio de resistência.</p>
<p>Com relação à homogeneidade, observando-se o coeficiente de variação:</p>
<ul>
<li>Grupo C = <strong>4,20% - Mais homogêneo;</strong></li>
<li>Grupo A = <strong>5,07%;</strong></li>
<li>Grupo B = <strong>5,84% - Menos homogêneo.</strong></li>
</ul>
<p>Em resumo, o grupo C combina a maior resistência média com a menor dispersão relativa.</p>
</section>
</section>
</section>
<section id="considerações-finais" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="considerações-finais"><span class="header-section-number">6</span> 🧠 Considerações finais</h2>
<p>Os quatro primeiros capítulos do livro fornecem uma base importante para o estudo da Estatística aplicada. Inicialmente, são apresentados conceitos fundamentais, como população, amostra, variável e dado. Em seguida, o livro aborda a organização dos dados por meio de tabelas, frequências e representações gráficas. Depois, são estudadas medidas que resumem os dados, como média, mediana e moda, além de medidas que avaliam a variabilidade, como amplitude, variância, desvio padrão, coeficiente de variação e erro padrão da média. Além disso, a inclusão dos conceitos de assimetria e curtose amplia a análise descritiva, pois permite compreender melhor o formato da distribuição dos dados complementando as medidas de posição e dispersão e oferecendo uma visão mais completa sobre o comportamento dos dados.</p>
<p>A introdução ao R mostra a importância do uso de ferramentas computacionais na Estatística. O R, em conjunto com o RStudio, permite realizar cálculos, organizar dados, construir gráficos e aplicar técnicas estatísticas com eficiência. Além disso, entender a sintaxe e a semântica do R é essencial para escrever comandos corretamente e interpretar o significado das operações realizadas. Assim, o aprendizado dos conceitos teóricos aliado ao uso de softwares estatísticos contribui para uma formação mais completa e aplicada, especialmente nas áreas de Engenharia e Ciências.</p>
<p>Conclui-se, com base na Estatística Descritiva, que o grupo C apresentou a maior resistência média e o menor coeficiente de variação, enquanto o grupo B apresentou resistência superior à do grupo A, mas também a maior dispersão. Entretanto, essas medidas permitem apenas organizar, resumir e comparar os dados observados, não sendo suficientes para generalizar os resultados ou tomar decisões sobre a população. Para verificar se as diferenças encontradas são estatisticamente significativas, torna-se necessária a aplicação da Estatística Inferencial, por meio de métodos como intervalos de confiança, testes de hipóteses e análise de variância. A decisão sobre o atendimento aos requisitos do projeto também deve considerar a resistência especificada, a idade de rompimento, o material, o plano de amostragem, a quantidade de exemplares e os critérios da norma técnica aplicável. Essas análises serão abordadas nos próximos relatórios.</p>
</section>
<section id="referências" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="referências"><span class="header-section-number">7</span> 📖 Referências</h2>
<p>Depois de inserido as informaçõe no arquivo <strong>referencias.bib</strong>, use:</p>
<ul>
<li>Segundo <span class="citation" data-cites="Rbasico2022">Batista e Oliveira (<a href="#ref-Rbasico2022" role="doc-biblioref">2022</a>)</span></li>
<li>Tudo é um objeto em R <span class="citation" data-cites="Rbasico2022">(<a href="#ref-Rbasico2022" role="doc-biblioref">Batista e Oliveira, 2022</a>)</span> <span class="citation" data-cites="batista2026EPAEC">(<a href="#ref-batista2026EPAEC" role="doc-biblioref"><strong>batista2026EPAEC?</strong></a>)</span></li>
</ul>
<!-- -->

</section>
</div>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Referências</h2><div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-Rbasico2022" class="csl-entry" role="listitem">
BATISTA, B. D. O.; OLIVEIRA, D. A. B. J. <strong>R básico</strong>. 1. ed. Ouro Branco, MG: [s.n.], 2022. p. 321
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Código fonte</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Só mude aqui!!!!</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Jair Malta e Wesley Pinheiro "</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Relatório de Aula Prática 01 - Teste"</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> referencias.bib</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># A partir daqui nao faca alteracoes!!!!!</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="an">link-citations:</span><span class="co"> true</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="an">csl:</span><span class="co"> associacao-brasileira-de-normas-tecnicas-ipea.csl</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "&lt;a href='https://bendeivide.github.io/courses/epaec/' target='_blank'&gt;Estatística e Probabilidade&lt;/a&gt; &lt;/br&gt; &lt;a href='https://bendeivide.github.io' target='_blank'&gt;Prof. Ben Dêivide (DEFIM/CAP/UFSJ)&lt;/a&gt;"</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="an">include-before-body:</span><span class="co"> header.html</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> now</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="an">date-format:</span><span class="co"> "DD/MM/YYYY, HH:mm"</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> pt-BR</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: bootstrap</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co">    #css: styles.css</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📌 Introdução</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>A Estatística é uma área fundamental para a análise, interpretação e tomada de decisão com base em dados. No contexto das Engenharias e Ciências, essa área permite transformar informações brutas em resultados organizados, facilitando a compreensão de fenômenos, processos e problemas reais. Por meio da estatística, podemos tomar decisões sobre uma população através da amostra, importante pois poupa tempo e dinheiro. </span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>Nesse primeiro momento, trataremos de Estatística Descritiva, apresentando conceitos como população, amostra, variável, dados, coleta, organização, tabelas de frequência, gráficos, medidas de posição, medidas de dispersão, assimetria e curtose. Esses conteúdos são essenciais para compreender como os dados podem ser tratados e resumidos antes da aplicação de técnicas estatísticas mais avançadas.  </span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>Além da estatística em sua essência, com o avanço das tecnologias a estatística manual e braçal cedeu espaço para softwares com grande capacidade de processamento de dados, como por exemplo o R Studio, que utiliza a linguagem de programação R em um ambiente computacional voltado principalmente para estatística, análise de dados e construção de gráficos. De forma simples, pode-se dizer que o R é a linguagem e o ambiente que executa os cálculos, enquanto o RStudio é a ferramenta que organiza e facilita o uso dessa linguagem. O RStudio permite escrever comandos, executar linhas de código, visualizar resultados, criar gráficos, consultar ajuda e gerenciar projetos. </span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🎯 Objetivos</span></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a><span class="fu">### Objetivo geral</span></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>Resumir os principais conceitos apresentados nos quatro primeiros capítulos do livro Estatística &amp; Probabilidade aplicada às Engenharias e Ciências; introduzir conceitos iniciais da linguagem R e do RStudio, por exemplo Sintaxe e Semântica; realizar uma aplicação prática unindo os 2 temas anteriores.</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a><span class="fu">### Objetivos específicos</span></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Apresentar as definições iniciais da Estatística, incluindo população, amostra, variável e dado; </span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Explicar a importância da coleta, organização e apresentação dos dados; </span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Descrever as principais medidas de posição, como média, mediana e moda; </span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Apresentar as principais medidas de dispersão, como amplitude, variância, desvio padrão, coeficiente de variação e erro padrão da média; </span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Apresentar os conceitos de assimetria e curtose; </span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Explicar conceitos e ideias iniciais da linguagem R e do RStudio. Passos iniciais, aplicações e sua sintaxe e Semântica. </span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Relacionar todos os itens e conceitos acima e realizar uma aplicação prática mesclando a estatística descritiva com a linguagem R e RStudio. </span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a><span class="fu">## ⚙️ Metodologia</span></span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">div</span><span class="ot"> style</span><span class="op">=</span><span class="st">"text-align: justify;"</span><span class="dt">&gt;</span></span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>Este relatório foi elaborado a partir da leitura e análise dos quatro primeiros capítulos do livro digital Estatística &amp; Probabilidade aplicada às Engenharias e Ciências, da visualização e compreensão dos vídeos do Curso R Básico 2024 e conteúdos auxiliares como o R Studio, Pacote Leem e Rmarkdown. A metodologia utilizada consistiu em identificar os principais conceitos, definições e aplicações sintetizando as ideias centrais de forma objetiva e organizada. </span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>A estrutura do relatório foi organizada em introdução, objetivos, metodologia, resultados e discussão, conclusão e referências. O foco foi produzir um resumo claro, com linguagem acadêmica simples e adequada. </span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🔍 Resultados e Discussão</span></span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a><span class="fu">### Capítulo 1: Definições Gerais da Estatística e técnicas de somatórios</span></span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a>O primeiro capítulo apresenta a Estatística como uma ciência voltada à coleta, organização, descrição, análise e interpretação de dados. Segunda Batista (2024) na era digital há uma grande produção de informações, especialmente em ambientes como redes sociais, plataformas digitais e sistemas corporativos, sendo necessário utilizar métodos estatísticos para compreender esses dados e auxiliar na tomada de decisões. </span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a>O capítulo diferencia três grandes áreas da Estatística: Estatística Descritiva, Probabilidade e Estatística Inferencial. A Estatística Descritiva reúne técnicas de coleta, organização, tabulação, representação gráfica e cálculo de medidas que resumem os dados. A Probabilidade é apresentada como a teoria matemática voltada ao estudo da incerteza em fenômenos aleatórios. Já a Estatística Inferencial busca utilizar informações de uma amostra para tirar conclusões sobre uma população. </span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a>Também são introduzidos conceitos básicos como população, amostra, variável e dado. </span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>População é o conjunto de elementos de interesse da pesquisa e amostra é um subconjunto dessa população;</span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Variável é a característica que se deseja estudar, sendo dividida em Qualitativa (Nomina e ordinal) e Quantitativa (Discreta e Contínua);</span>
<span id="cb5-74"><a href="#cb5-74" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Dado é o valor observado dessa característica em cada elemento. </span>
<span id="cb5-75"><a href="#cb5-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-76"><a href="#cb5-76" aria-hidden="true" tabindex="-1"></a>O capítulo ainda relaciona a Estatística ao método científico, destacando etapas como identificação do problema, formulação de hipóteses, revisão de literatura, coleta de dados, análise e apresentação dos resultados. </span>
<span id="cb5-77"><a href="#cb5-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-78"><a href="#cb5-78" aria-hidden="true" tabindex="-1"></a><span class="fu">### Capítulo 2: Coleta, organização e apresentação dos dados</span></span>
<span id="cb5-79"><a href="#cb5-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-80"><a href="#cb5-80" aria-hidden="true" tabindex="-1"></a>O segundo capítulo trata da etapa posterior à definição da população e das variáveis de interesse: a coleta e organização dos dados. O autor explica que os dados coletados sem ordenação ou arranjo sistemático são chamados de dados brutos. Quando esses dados são organizados em ordem crescente ou decrescente, passam a ser chamados de dados em rol ou dados elaborados. </span>
<span id="cb5-81"><a href="#cb5-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-82"><a href="#cb5-82" aria-hidden="true" tabindex="-1"></a>Um dos principais pontos do capítulo é a construção de tabelas de frequência. A frequência absoluta indica quantas vezes determinado valor aparece no conjunto de dados, enquanto a frequência relativa representa essa ocorrência em relação ao total de observações. A frequência percentual transforma a frequência relativa em porcentagem, facilitando a interpretação. O capítulo também apresenta frequências acumuladas, que permitem responder perguntas como “quantos valores estão abaixo de determinado ponto?” ou “quantos valores estão acima de determinado ponto?”. </span>
<span id="cb5-83"><a href="#cb5-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-84"><a href="#cb5-84" aria-hidden="true" tabindex="-1"></a>O capítulo 2 apresenta como utilizar o pacote leem para tabular dados e também como instalar o pacote propriamente dito no RStudio.</span>
<span id="cb5-85"><a href="#cb5-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-86"><a href="#cb5-86" aria-hidden="true" tabindex="-1"></a>Além das tabelas, o capítulo discute o agrupamento de variáveis quantitativas contínuas em intervalos de classe. Esse procedimento é importante quando há muitos dados ou quando os valores não são naturalmente discretos. O autor apresenta critérios para definir o número de classes, a amplitude total e a amplitude de cada classe, mostrando a importância da organização dos dados para facilitar sua leitura, interpretação e apresentação. </span>
<span id="cb5-87"><a href="#cb5-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-88"><a href="#cb5-88" aria-hidden="true" tabindex="-1"></a>É apresentado também representações gráficas, ferramentas que facilitam a visualização mesmo em situações de complexidade, ajudando assim na análise e compreensão. São citados tipos de gráficos como gráfico de barras, histogramas, gráfico de linhas, gráfico de dispersão. É mencionado também, no ambiente R, o pacote “graphics” e o “ggplot2” que auxiliam no tratamento dos dados e criação dos gráficos no RStudio.  </span>
<span id="cb5-89"><a href="#cb5-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-90"><a href="#cb5-90" aria-hidden="true" tabindex="-1"></a><span class="fu">### Capítulo 3: Medidas de Posição</span></span>
<span id="cb5-91"><a href="#cb5-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-92"><a href="#cb5-92" aria-hidden="true" tabindex="-1"></a>O terceiro capítulo apresenta as medidas de posição, também chamadas de medidas de tendência central. Essas medidas são utilizadas para resumir um conjunto de dados por meio de valores representativos, indicando em torno de qual ponto os dados se concentram. As principais medidas estudadas são a média aritmética, a mediana e a moda. </span>
<span id="cb5-93"><a href="#cb5-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-94"><a href="#cb5-94" aria-hidden="true" tabindex="-1"></a>A média aritmética, populacional (Equação 1) e amostral (Equação 2) é apresentada como uma das medidas mais conhecidas e utilizadas. Ela representa um ponto de equilíbrio dos dados e pode ser calculada tanto para dados não agrupados quanto para dados agrupados. No entanto, o capítulo destaca que a média é sensível a valores discrepantes, ou seja, valores muito distantes da maioria das observações podem alterar significativamente seu resultado. Para esses casos sugere-se a utilização da média aparada(Equação 3), onde é excluído do cálculo o valor mínimo e máximo de um conjunto de dados.</span>
<span id="cb5-95"><a href="#cb5-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-96"><a href="#cb5-96" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-97"><a href="#cb5-97" aria-hidden="true" tabindex="-1"></a>\mu = \frac{1}{N}\sum_{i=1}^{N} x_i \tag{1}</span>
<span id="cb5-98"><a href="#cb5-98" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-99"><a href="#cb5-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-100"><a href="#cb5-100" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-101"><a href="#cb5-101" aria-hidden="true" tabindex="-1"></a>\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i \tag{2}</span>
<span id="cb5-102"><a href="#cb5-102" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-103"><a href="#cb5-103" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-104"><a href="#cb5-104" aria-hidden="true" tabindex="-1"></a>\bar{x}_{trim} =</span>
<span id="cb5-105"><a href="#cb5-105" aria-hidden="true" tabindex="-1"></a>\frac{1}{n - 2k}</span>
<span id="cb5-106"><a href="#cb5-106" aria-hidden="true" tabindex="-1"></a>\sum_{i=k+1}^{n-k} x_{(i)} \tag{3}</span>
<span id="cb5-107"><a href="#cb5-107" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-108"><a href="#cb5-108" aria-hidden="true" tabindex="-1"></a>A mediana é definida como o valor central de um conjunto de dados ordenado (Equações 4 e 5). Ela divide o conjunto em duas partes, de modo que aproximadamente 50% dos valores fiquem abaixo e 50% fiquem acima. Por considerar a posição dos dados e não diretamente seus valores extremos, a mediana é menos influenciada por dados discrepantes/extremos. Quando há dados agrupados em intervalos de classes o cálculo utiliza outros parâmetros, como limite inferior e superior da classe, frequência acumulada da classe anterior à classe em questão e frequência absoluta da classe mediana. </span>
<span id="cb5-109"><a href="#cb5-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-110"><a href="#cb5-110" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-111"><a href="#cb5-111" aria-hidden="true" tabindex="-1"></a>\begin{equation}</span>
<span id="cb5-112"><a href="#cb5-112" aria-hidden="true" tabindex="-1"></a>\text{Mediana} =</span>
<span id="cb5-113"><a href="#cb5-113" aria-hidden="true" tabindex="-1"></a>\begin{cases}</span>
<span id="cb5-114"><a href="#cb5-114" aria-hidden="true" tabindex="-1"></a>x_{(\frac{N+1}{2})}, &amp; \text{se } N \text{ ímpar} <span class="sc">\\</span></span>
<span id="cb5-115"><a href="#cb5-115" aria-hidden="true" tabindex="-1"></a>\frac{x_{(\frac{N}{2})} + x_{(\frac{N}{2}+1})}{2}, &amp; \text{se } N \text{ par}</span>
<span id="cb5-116"><a href="#cb5-116" aria-hidden="true" tabindex="-1"></a>\end{cases}</span>
<span id="cb5-117"><a href="#cb5-117" aria-hidden="true" tabindex="-1"></a>\tag{4}</span>
<span id="cb5-118"><a href="#cb5-118" aria-hidden="true" tabindex="-1"></a>\end{equation}</span>
<span id="cb5-119"><a href="#cb5-119" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-120"><a href="#cb5-120" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-121"><a href="#cb5-121" aria-hidden="true" tabindex="-1"></a>\begin{equation}</span>
<span id="cb5-122"><a href="#cb5-122" aria-hidden="true" tabindex="-1"></a>\tilde{x} =</span>
<span id="cb5-123"><a href="#cb5-123" aria-hidden="true" tabindex="-1"></a>\begin{cases}</span>
<span id="cb5-124"><a href="#cb5-124" aria-hidden="true" tabindex="-1"></a>x_{(\frac{n+1}{2})}, &amp; \text{se } n \text{ ímpar} <span class="sc">\\</span></span>
<span id="cb5-125"><a href="#cb5-125" aria-hidden="true" tabindex="-1"></a>\frac{x_{(\frac{n}{2})} + x_{(\frac{n}{2}+1})}{2}, &amp; \text{se } n \text{ par}</span>
<span id="cb5-126"><a href="#cb5-126" aria-hidden="true" tabindex="-1"></a>\end{cases}</span>
<span id="cb5-127"><a href="#cb5-127" aria-hidden="true" tabindex="-1"></a>\tag{5}</span>
<span id="cb5-128"><a href="#cb5-128" aria-hidden="true" tabindex="-1"></a>\end{equation}</span>
<span id="cb5-129"><a href="#cb5-129" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb5-130"><a href="#cb5-130" aria-hidden="true" tabindex="-1"></a>A moda, por sua vez, representa o valor mais frequente em um conjunto de dados e pode ser aplicada a diferentes tipos de variáveis, inclusive qualitativas. Vale destacar que, um conjunto de dados poderá ter mais de uma moda, isto é, se observarmos dois valores mais frequentes e iguais, teremos uma distribuição bimodal. Da mesma forma que a mediana, a moda não é influenciada por valores extremos, desde que estes não pertençam a classe modal.</span>
<span id="cb5-131"><a href="#cb5-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-132"><a href="#cb5-132" aria-hidden="true" tabindex="-1"></a>O capítulo também mostra que média, mediana e moda podem oferecer interpretações diferentes de um mesmo conjunto de dados. Em distribuições mais simétricas, essas medidas tendem a se aproximar. Em distribuições assimétricas ou com valores extremos, elas podem apresentar diferenças importantes, sendo necessário escolher a medida mais adequada conforme a natureza dos dados e o objetivo da análise. </span>
<span id="cb5-133"><a href="#cb5-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-134"><a href="#cb5-134" aria-hidden="true" tabindex="-1"></a>Por fim é apresentado como o Pacote leem pode contribuir para o cálculo rápido das medidas média, mediana e moda utilizando as funções mean(), median() e mfreq(), respectivamente.</span>
<span id="cb5-135"><a href="#cb5-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-136"><a href="#cb5-136" aria-hidden="true" tabindex="-1"></a><span class="fu">### Capítulo 4: Medidas de dispersão</span></span>
<span id="cb5-137"><a href="#cb5-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-138"><a href="#cb5-138" aria-hidden="true" tabindex="-1"></a>O quarto capítulo complementa o estudo das medidas de posição ao apresentar as medidas de dispersão. É apresentado que conjuntos de dados diferentes podem possuir a mesma média, mas apresentar comportamentos distintos. Isso demonstra que apenas uma medida central não é suficiente para caracterizar adequadamente os dados. </span>
<span id="cb5-139"><a href="#cb5-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-140"><a href="#cb5-140" aria-hidden="true" tabindex="-1"></a>A primeira medida apresentada é a amplitude, definida como a diferença entre o maior e o menor valor do conjunto. Embora seja simples de calcular e esteja na mesma unidade da variável, a amplitude possui limitações, pois considera apenas os valores extremos e ignora o comportamento dos demais dados. Por isso, a amplitude pode não representar adequadamente a variabilidade total de um conjunto. </span>
<span id="cb5-141"><a href="#cb5-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-142"><a href="#cb5-142" aria-hidden="true" tabindex="-1"></a>Em seguida, o capítulo apresenta a variância, que mede a dispersão dos dados em relação à média por meio dos desvios ao quadrado. A variância considera todos os valores do conjunto, sendo uma medida mais completa do que a amplitude. Entretanto, sua unidade fica elevada ao quadrado, o que pode dificultar a interpretação prática. Por esse motivo, utiliza-se também o desvio padrão, que corresponde à raiz quadrada da variância e retorna a medida de dispersão para a mesma unidade da variável analisada. </span>
<span id="cb5-143"><a href="#cb5-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-144"><a href="#cb5-144" aria-hidden="true" tabindex="-1"></a>É importante saber que quanto mais próximo de zero a variância e o desvio padrão for, mais concentrado e melhor representado os dados estão com relação à média. Além disso, para utilizar variância e desvio padrão para comparar grupos de dados, temos que verificar se a média desses grupos são iguais e se as observações estão na mesma unidade de mensuração. </span>
<span id="cb5-145"><a href="#cb5-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-146"><a href="#cb5-146" aria-hidden="true" tabindex="-1"></a>O capítulo também aborda o coeficiente de variação, uma medida relativa de dispersão que expressa o desvio padrão em relação à média, geralmente em porcentagem. Essa medida permite comparar a variabilidade entre grupos diferentes, desde que a variável analisada possua uma escala adequada. Por fim, o autor apresenta o erro padrão da média, que está relacionado à precisão com que a média amostral estima a média populacional e será importante em conteúdos posteriores, como estimação e testes de hipóteses. </span>
<span id="cb5-147"><a href="#cb5-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-148"><a href="#cb5-148" aria-hidden="true" tabindex="-1"></a><span class="fu">### Assimetria e curtose</span></span>
<span id="cb5-149"><a href="#cb5-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-150"><a href="#cb5-150" aria-hidden="true" tabindex="-1"></a>Além das medidas de posição e dispersão, a análise estatística também pode considerar medidas relacionadas ao formato da distribuição dos dados, como a assimetria e a curtose. Essas medidas ajudam a compreender não apenas onde os dados se concentram e o quanto variam, mas também como os valores estão distribuídos ao redor da média. A assimetria indica o grau de afastamento de uma distribuição em relação à simetria, ou seja, descreve o equilíbrio da distribuição. A curtose ajuda a avaliar o peso das caudas e a ocorrência de valores extremos.</span>
<span id="cb5-151"><a href="#cb5-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-152"><a href="#cb5-152" aria-hidden="true" tabindex="-1"></a>Uma distribuição é considerada aproximadamente simétrica quando os dados se distribuem de forma semelhante dos dois lados de uma medida central. Nesse caso, média, mediana e moda tendem a apresentar valores próximos. Quando a distribuição possui uma cauda mais alongada para a direita, ocorre assimetria positiva. Nesse tipo de situação, alguns valores altos podem puxar a média para cima. Quando a cauda é mais alongada para a esquerda, ocorre assimetria negativa, indicando a presença de valores baixos que influenciam a distribuição.</span>
<span id="cb5-153"><a href="#cb5-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-154"><a href="#cb5-154" aria-hidden="true" tabindex="-1"></a>A análise da assimetria é importante porque permite avaliar se a média representa bem o conjunto de dados. Em distribuições muito assimétricas, a média pode ser fortemente afetada por valores extremos, sendo recomendável observar também a mediana e a moda. Dessa forma, a assimetria se relaciona diretamente ao conteúdo do Capítulo 3 do livro, no qual são discutidas as medidas de posição e suas diferentes interpretações. </span>
<span id="cb5-155"><a href="#cb5-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-156"><a href="#cb5-156" aria-hidden="true" tabindex="-1"></a>A curtose está relacionada ao grau de concentração dos dados em torno do centro da distribuição e ao peso das caudas. De forma geral, a curtose ajuda a identificar se uma distribuição apresenta maior concentração de valores próximos à média ou maior ocorrência de valores extremos. Uma distribuição com curtose mais elevada tende a indicar maior presença de valores extremos ou caudas mais pesadas. Já uma curtose menor indica uma distribuição mais achatada, com menor concentração central ou caudas menos intensas.</span>
<span id="cb5-157"><a href="#cb5-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-158"><a href="#cb5-158" aria-hidden="true" tabindex="-1"></a>Em suma, assimetria e curtose complementam as medidas de dispersão estudadas no Capítulo 4. Enquanto a variância, o desvio padrão e o coeficiente de variação indicam o nível de variabilidade, a assimetria e a curtose ajudam a interpretar o formato da distribuição e a presença de valores extremos. </span>
<span id="cb5-159"><a href="#cb5-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-160"><a href="#cb5-160" aria-hidden="true" tabindex="-1"></a><span class="fu">### Introdução básica ao R (linguagem e software)</span></span>
<span id="cb5-161"><a href="#cb5-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-162"><a href="#cb5-162" aria-hidden="true" tabindex="-1"></a>O R é uma linguagem de programação e um ambiente computacional voltado principalmente para estatística, análise de dados e construção de gráficos. O projeto R apresenta o software como um ambiente gratuito para computação estatística e gráficos, disponível para diferentes sistemas operacionais. </span>
<span id="cb5-163"><a href="#cb5-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-164"><a href="#cb5-164" aria-hidden="true" tabindex="-1"></a>Para utilizar o R, é necessário instalar inicialmente o programa R, que executa os comandos estatísticos. A instalação pode ser feita pelo site oficial do projeto R, por meio da rede CRAN. Após instalar o R, recomenda-se instalar também o RStudio, que é uma interface de desenvolvimento integrada. O RStudio facilita o uso do R, pois reúne editor de código, console, gráficos, ambiente de trabalho, arquivos, pacotes e ajuda integrada em uma única interface. </span>
<span id="cb5-165"><a href="#cb5-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-166"><a href="#cb5-166" aria-hidden="true" tabindex="-1"></a>De forma simples, pode-se dizer que o R é a linguagem e o ambiente que executa os cálculos, enquanto o RStudio é a ferramenta que organiza e facilita o uso dessa linguagem. O RStudio permite escrever comandos, executar linhas de código, visualizar resultados, criar gráficos, consultar ajuda e gerenciar projetos, além de possuir pacotes com integração à internet, por exemplo o HTML, para criação de relatórios, apresentações e outros diversos itens. Sua interface é dividida em 4 quadrantes sendo:</span>
<span id="cb5-167"><a href="#cb5-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-168"><a href="#cb5-168" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>1º Quadrante – Script do R - Área utilizada para escrever, editar e salvar os códigos em arquivos com extensão .R; </span>
<span id="cb5-169"><a href="#cb5-169" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>2º Quadrante – Console do R - Local onde os comandos são efetivamente executados e os resultados aparecem. Também permite digitar comandos diretamente, porém esses comandos não ficam organizados em um script, a menos que sejam salvos separadamente;</span>
<span id="cb5-170"><a href="#cb5-170" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>3º Quadrante – Ambiente Global - Exibe os objetos criados durante a análise, como vetores, tabelas, conjuntos de dados, funções e resultados de cálculos. Também apresenta o histórico dos comandos executados e permite acompanhar os dados armazenados na sessão atual;</span>
<span id="cb5-171"><a href="#cb5-171" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>4º Quadrante – Área de plotagem - Utilizado para visualizar gráficos, consultar arquivos e pastas, gerenciar pacotes e acessar a documentação de ajuda das funções. </span>
<span id="cb5-172"><a href="#cb5-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-173"><a href="#cb5-173" aria-hidden="true" tabindex="-1"></a><span class="fu">### Sintaxe e semântica do R</span></span>
<span id="cb5-174"><a href="#cb5-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-175"><a href="#cb5-175" aria-hidden="true" tabindex="-1"></a>A linguagem R, assim como outras linguagens de programação, possui sintaxe e semântica. A sintaxe está relacionada à forma correta de escrever os comandos. Em outras palavras, a sintaxe define as regras de escrita que o R reconhece. Se um comando for escrito de forma incorreta, o programa poderá apresentar erro.</span>
<span id="cb5-176"><a href="#cb5-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-177"><a href="#cb5-177" aria-hidden="true" tabindex="-1"></a>Por exemplo, para criar um conjunto de dados no R, pode-se usar o comando:</span>
<span id="cb5-178"><a href="#cb5-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-179"><a href="#cb5-179" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>dados &lt;- c (3, 1, 0, 1, 3, 2, 4, 1, 3, 1)</span>
<span id="cb5-180"><a href="#cb5-180" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-181"><a href="#cb5-181" aria-hidden="true" tabindex="-1"></a>Nesse exemplo, dados é o nome do objeto criado, &lt;- é o operador de atribuição, e c() é uma função usada para combinar valores em um vetor. A escrita correta dos parênteses, vírgulas e símbolos faz parte da sintaxe da linguagem.</span>
<span id="cb5-182"><a href="#cb5-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-183"><a href="#cb5-183" aria-hidden="true" tabindex="-1"></a>A semântica, por outro lado, diz respeito ao significado dos comandos. Ou seja, enquanto a sintaxe trata da forma correta de escrever, a semântica trata do que aquele comando representa ou executa. No exemplo anterior, o significado do comando é armazenar uma sequência de valores numéricos dentro de um objeto chamado dados.</span>
<span id="cb5-184"><a href="#cb5-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-185"><a href="#cb5-185" aria-hidden="true" tabindex="-1"></a>Após criar esse objeto, é possível aplicar funções estatísticas:</span>
<span id="cb5-186"><a href="#cb5-186" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>mean(dados) # calcula a média</span>
<span id="cb5-187"><a href="#cb5-187" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>median(dados) # calcula a mediana</span>
<span id="cb5-188"><a href="#cb5-188" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>var(dados) # calcula a variância</span>
<span id="cb5-189"><a href="#cb5-189" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>sd(dados) # calcula o desvio padrão</span>
<span id="cb5-190"><a href="#cb5-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-191"><a href="#cb5-191" aria-hidden="true" tabindex="-1"></a>A sintaxe desses comandos envolve o nome da função, como mean, median, var e sd, seguido dos parênteses com o objeto analisado. Já a semântica está no significado de cada função. A função mean() calcula a média aritmética, median() calcula a mediana, var() calcula a variância e sd() calcula o desvio padrão.</span>
<span id="cb5-192"><a href="#cb5-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-193"><a href="#cb5-193" aria-hidden="true" tabindex="-1"></a>Outro ponto importante da sintaxe do R é que a linguagem diferencia letras maiúsculas de minúsculas. Assim, um objeto chamado dados é diferente de outro chamado Dados. Também é comum usar comentários no código, iniciados pelo símbolo #. Os comentários não são executados pelo R, servindo apenas para explicar o código.</span>
<span id="cb5-194"><a href="#cb5-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-195"><a href="#cb5-195" aria-hidden="true" tabindex="-1"></a>Portanto, compreender sintaxe e semântica é essencial para utilizar o R corretamente. A sintaxe permite escrever comandos sem erros, enquanto a semântica permite entender o significado das operações realizadas. Esse conhecimento é importante para aplicar os conceitos estatísticos estudados, como organização de dados, medidas de posição, medidas de dispersão, assimetria e curtose.</span>
<span id="cb5-196"><a href="#cb5-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-197"><a href="#cb5-197" aria-hidden="true" tabindex="-1"></a><span class="fu">## Estudo de Caso e Aplicação</span></span>
<span id="cb5-198"><a href="#cb5-198" aria-hidden="true" tabindex="-1"></a><span class="fu">### Contexto do Projeto</span></span>
<span id="cb5-199"><a href="#cb5-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-200"><a href="#cb5-200" aria-hidden="true" tabindex="-1"></a>A obra em questão consiste na execução de um muro de arrimo em concreto armado, com função estrutural de contenção de um talude de mineração (cava de extração de minério de ferro). O muro possui altura média de 12 m, extensão linear de 180 m e volume total estimado de concreto de 2.400 m³. </span>
<span id="cb5-201"><a href="#cb5-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-202"><a href="#cb5-202" aria-hidden="true" tabindex="-1"></a>A resistência característica à compressão (fck) de projeto especificada no memorial de cálculo é de 30 MPa (30.000 kPa), para que o elemento suporte os empuxos de terra, sobrecargas de equipamentos e ações hidrostáticas. </span>
<span id="cb5-203"><a href="#cb5-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-204"><a href="#cb5-204" aria-hidden="true" tabindex="-1"></a>O concreto foi dosado em usina própria da mineradora, com traço 1:2,5:3,0 (cimento<span class="sc">:areia:</span> brita), relação a/c = 0,48 e adição de superplastificante à base de policarboxilato para garantir trabalhabilidade (slump de 120 ± 20 mm) mesmo com alta densidade de armadura.</span>
<span id="cb5-205"><a href="#cb5-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-206"><a href="#cb5-206" aria-hidden="true" tabindex="-1"></a><span class="fu">### Plano de Amostragem e Produção </span></span>
<span id="cb5-207"><a href="#cb5-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-208"><a href="#cb5-208" aria-hidden="true" tabindex="-1"></a>A concretagem do muro foi dividida em 3 dias consecutivos de produção, denominados Grupo A, B e C, correspondentes a: </span>
<span id="cb5-209"><a href="#cb5-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-210"><a href="#cb5-210" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Grupo A (Dia 1 – 08/08/2026): concretagem da base e primeira elevação (1/3 do muro) – 17 corpos de prova. </span>
<span id="cb5-211"><a href="#cb5-211" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Grupo B (Dia 2 – 09/08/2026): concretagem da segunda elevação (trecho central) – 18 corpos de prova. </span>
<span id="cb5-212"><a href="#cb5-212" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Grupo C (Dia 3 – 10/08/2026): concretagem da coroa e fechamento superior – 15 corpos de prova. </span>
<span id="cb5-213"><a href="#cb5-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-214"><a href="#cb5-214" aria-hidden="true" tabindex="-1"></a>Cada dia de produção correspondeu a um caminhão betoneira diferente (mesmo traço, mas com pequenas variações inerentes à umidade dos agregados e ao tempo de mistura), o que justifica a separação em grupos para fins de rastreabilidade.</span>
<span id="cb5-215"><a href="#cb5-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-216"><a href="#cb5-216" aria-hidden="true" tabindex="-1"></a><span class="fu">### Coleta e Preparação dos Corpos de Prova </span></span>
<span id="cb5-217"><a href="#cb5-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-218"><a href="#cb5-218" aria-hidden="true" tabindex="-1"></a>Em cada dia de concretagem, foram moldados corpos de prova cilíndricos (dimensões: 10 cm × 20 cm), conforme prescrições da NBR 5738. A amostragem foi feita no ponto de descarga do caminhão betoneira, imediatamente antes do lançamento no muro, seguindo o critério de 1 corpo de prova a cada 50 m³ de concreto lançado (excedendo o mínimo normativo para garantir robustez estatística). </span>
<span id="cb5-219"><a href="#cb5-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-220"><a href="#cb5-220" aria-hidden="true" tabindex="-1"></a>Os corpos de prova foram: </span>
<span id="cb5-221"><a href="#cb5-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-222"><a href="#cb5-222" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Desmoldados após 24 horas; </span>
<span id="cb5-223"><a href="#cb5-223" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Cura úmida em câmara úmida (temperatura 23 ± 2 °C e umidade relativa ≥ 95%) por 7 dias; </span>
<span id="cb5-224"><a href="#cb5-224" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Mantidos em condição ambiente do laboratório até a data do ensaio (aos 28 dias). </span>
<span id="cb5-225"><a href="#cb5-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-226"><a href="#cb5-226" aria-hidden="true" tabindex="-1"></a>Os resultados obtidos podem ser observados na </span>
<span id="cb5-227"><a href="#cb5-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-228"><a href="#cb5-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-231"><a href="#cb5-231" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb5-232"><a href="#cb5-232" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb5-233"><a href="#cb5-233" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb5-234"><a href="#cb5-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-235"><a href="#cb5-235" aria-hidden="true" tabindex="-1"></a>corposdeprova <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/Users/Dell/Desktop/relatórios/relatorio-eait/relatorio/rel01/corposdeprova.csv"</span>)</span>
<span id="cb5-236"><a href="#cb5-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-237"><a href="#cb5-237" aria-hidden="true" tabindex="-1"></a><span class="co"># Número de colunas (para aplicar centralização em todas)</span></span>
<span id="cb5-238"><a href="#cb5-238" aria-hidden="true" tabindex="-1"></a>n_col <span class="ot">&lt;-</span> <span class="fu">ncol</span>(corposdeprova)</span>
<span id="cb5-239"><a href="#cb5-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-240"><a href="#cb5-240" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(corposdeprova, </span>
<span id="cb5-241"><a href="#cb5-241" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Dados dos Corpos de Prova"</span>,</span>
<span id="cb5-242"><a href="#cb5-242" aria-hidden="true" tabindex="-1"></a>      <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb5-243"><a href="#cb5-243" aria-hidden="true" tabindex="-1"></a>      <span class="at">align =</span> <span class="fu">rep</span>(<span class="st">"c"</span>, n_col)) <span class="sc">%&gt;%</span>  <span class="co"># garante todas as colunas centralizadas</span></span>
<span id="cb5-244"><a href="#cb5-244" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>),</span>
<span id="cb5-245"><a href="#cb5-245" aria-hidden="true" tabindex="-1"></a>                <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb5-246"><a href="#cb5-246" aria-hidden="true" tabindex="-1"></a>                <span class="at">position =</span> <span class="st">"center"</span>) <span class="sc">%&gt;%</span>  <span class="co"># centraliza a tabela na página</span></span>
<span id="cb5-247"><a href="#cb5-247" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span><span class="sc">:</span>n_col, <span class="at">extra_css =</span> <span class="st">"text-align: center;"</span>) <span class="sc">%&gt;%</span>  <span class="co"># força centralização</span></span>
<span id="cb5-248"><a href="#cb5-248" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scroll_box</span>(<span class="at">width =</span> <span class="st">"100%"</span>, <span class="at">height =</span> <span class="st">"400px"</span>)</span>
<span id="cb5-249"><a href="#cb5-249" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-250"><a href="#cb5-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-253"><a href="#cb5-253" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb5-254"><a href="#cb5-254" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leem)</span>
<span id="cb5-255"><a href="#cb5-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-256"><a href="#cb5-256" aria-hidden="true" tabindex="-1"></a><span class="co"># Carregar dados</span></span>
<span id="cb5-257"><a href="#cb5-257" aria-hidden="true" tabindex="-1"></a>corposdeprova <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/Users/Dell/Desktop/relatórios/relatorio-eait/relatorio/rel01/corposdeprova.csv"</span>)</span>
<span id="cb5-258"><a href="#cb5-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-259"><a href="#cb5-259" aria-hidden="true" tabindex="-1"></a><span class="co"># ==================== GRUPO A ====================</span></span>
<span id="cb5-260"><a href="#cb5-260" aria-hidden="true" tabindex="-1"></a>dados_A <span class="ot">&lt;-</span> corposdeprova<span class="sc">$</span>Resistencia_kPa[corposdeprova<span class="sc">$</span>Grupo <span class="sc">==</span> <span class="st">"A"</span>]</span>
<span id="cb5-261"><a href="#cb5-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-262"><a href="#cb5-262" aria-hidden="true" tabindex="-1"></a><span class="co"># Média (kPa → MPa)</span></span>
<span id="cb5-263"><a href="#cb5-263" aria-hidden="true" tabindex="-1"></a>media_A_MPa <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados_A) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-264"><a href="#cb5-264" aria-hidden="true" tabindex="-1"></a>media_A_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(media_A_MPa, <span class="dv">2</span>)</span>
<span id="cb5-265"><a href="#cb5-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-266"><a href="#cb5-266" aria-hidden="true" tabindex="-1"></a><span class="co"># Mediana (kPa → MPa)</span></span>
<span id="cb5-267"><a href="#cb5-267" aria-hidden="true" tabindex="-1"></a>mediana_A_MPa <span class="ot">&lt;-</span> <span class="fu">median</span>(dados_A) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-268"><a href="#cb5-268" aria-hidden="true" tabindex="-1"></a>mediana_A_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(mediana_A_MPa, <span class="dv">2</span>)</span>
<span id="cb5-269"><a href="#cb5-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-270"><a href="#cb5-270" aria-hidden="true" tabindex="-1"></a><span class="co"># Desvio Padrão (kPa → MPa)</span></span>
<span id="cb5-271"><a href="#cb5-271" aria-hidden="true" tabindex="-1"></a>desvio_A <span class="ot">&lt;-</span> <span class="fu">sd</span>(dados_A) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-272"><a href="#cb5-272" aria-hidden="true" tabindex="-1"></a>desvio_A_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(desvio_A, <span class="dv">2</span>)</span>
<span id="cb5-273"><a href="#cb5-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-274"><a href="#cb5-274" aria-hidden="true" tabindex="-1"></a><span class="co"># Variância (kPa² → MPa²)</span></span>
<span id="cb5-275"><a href="#cb5-275" aria-hidden="true" tabindex="-1"></a>variancia_A <span class="ot">&lt;-</span> <span class="fu">var</span>(dados_A) <span class="sc">/</span> (<span class="dv">1000</span><span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb5-276"><a href="#cb5-276" aria-hidden="true" tabindex="-1"></a>variancia_A_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(variancia_A, <span class="dv">2</span>)</span>
<span id="cb5-277"><a href="#cb5-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-278"><a href="#cb5-278" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficiente de Variação (mesmo em %)</span></span>
<span id="cb5-279"><a href="#cb5-279" aria-hidden="true" tabindex="-1"></a>cv_A <span class="ot">&lt;-</span> (<span class="fu">sd</span>(dados_A) <span class="sc">/</span> <span class="fu">mean</span>(dados_A)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb5-280"><a href="#cb5-280" aria-hidden="true" tabindex="-1"></a>cv_A_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(cv_A, <span class="dv">2</span>)</span>
<span id="cb5-281"><a href="#cb5-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-282"><a href="#cb5-282" aria-hidden="true" tabindex="-1"></a><span class="co"># Assimetria (adimensional)</span></span>
<span id="cb5-283"><a href="#cb5-283" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(dados_A)</span>
<span id="cb5-284"><a href="#cb5-284" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_A <span class="sc">-</span> <span class="fu">mean</span>(dados_A))<span class="sc">^</span><span class="dv">3</span>) <span class="sc">/</span> n</span>
<span id="cb5-285"><a href="#cb5-285" aria-hidden="true" tabindex="-1"></a>s3 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_A <span class="sc">-</span> <span class="fu">mean</span>(dados_A))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span>(<span class="dv">3</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb5-286"><a href="#cb5-286" aria-hidden="true" tabindex="-1"></a>assimetria_A <span class="ot">&lt;-</span> m3 <span class="sc">/</span> s3</span>
<span id="cb5-287"><a href="#cb5-287" aria-hidden="true" tabindex="-1"></a>assimetria_A_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(assimetria_A, <span class="dv">3</span>)</span>
<span id="cb5-288"><a href="#cb5-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-289"><a href="#cb5-289" aria-hidden="true" tabindex="-1"></a><span class="co"># Curtose (adimensional)</span></span>
<span id="cb5-290"><a href="#cb5-290" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_A <span class="sc">-</span> <span class="fu">mean</span>(dados_A))<span class="sc">^</span><span class="dv">4</span>) <span class="sc">/</span> n</span>
<span id="cb5-291"><a href="#cb5-291" aria-hidden="true" tabindex="-1"></a>s4 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_A <span class="sc">-</span> <span class="fu">mean</span>(dados_A))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb5-292"><a href="#cb5-292" aria-hidden="true" tabindex="-1"></a>curtose_A <span class="ot">&lt;-</span> m4 <span class="sc">/</span> s4</span>
<span id="cb5-293"><a href="#cb5-293" aria-hidden="true" tabindex="-1"></a>curtose_A_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(curtose_A, <span class="dv">3</span>)</span>
<span id="cb5-294"><a href="#cb5-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-295"><a href="#cb5-295" aria-hidden="true" tabindex="-1"></a><span class="co"># Mínimo (kPa → MPa)</span></span>
<span id="cb5-296"><a href="#cb5-296" aria-hidden="true" tabindex="-1"></a>min_A <span class="ot">&lt;-</span> <span class="fu">min</span>(dados_A) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-297"><a href="#cb5-297" aria-hidden="true" tabindex="-1"></a>min_A_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(min_A, <span class="dv">2</span>)</span>
<span id="cb5-298"><a href="#cb5-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-299"><a href="#cb5-299" aria-hidden="true" tabindex="-1"></a><span class="co"># Máximo (kPa → MPa)</span></span>
<span id="cb5-300"><a href="#cb5-300" aria-hidden="true" tabindex="-1"></a>max_A <span class="ot">&lt;-</span> <span class="fu">max</span>(dados_A) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-301"><a href="#cb5-301" aria-hidden="true" tabindex="-1"></a>max_A_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(max_A, <span class="dv">2</span>)</span>
<span id="cb5-302"><a href="#cb5-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-303"><a href="#cb5-303" aria-hidden="true" tabindex="-1"></a><span class="co"># Amplitude Total (kPa → MPa)</span></span>
<span id="cb5-304"><a href="#cb5-304" aria-hidden="true" tabindex="-1"></a>amplitude_A <span class="ot">&lt;-</span> (<span class="fu">max</span>(dados_A) <span class="sc">-</span> <span class="fu">min</span>(dados_A)) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-305"><a href="#cb5-305" aria-hidden="true" tabindex="-1"></a>amplitude_A_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(amplitude_A, <span class="dv">2</span>)</span>
<span id="cb5-306"><a href="#cb5-306" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-307"><a href="#cb5-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-310"><a href="#cb5-310" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb5-311"><a href="#cb5-311" aria-hidden="true" tabindex="-1"></a><span class="co"># ==================== GRUPO B ====================</span></span>
<span id="cb5-312"><a href="#cb5-312" aria-hidden="true" tabindex="-1"></a>dados_B <span class="ot">&lt;-</span> corposdeprova<span class="sc">$</span>Resistencia_kPa[corposdeprova<span class="sc">$</span>Grupo <span class="sc">==</span> <span class="st">"B"</span>]</span>
<span id="cb5-313"><a href="#cb5-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-314"><a href="#cb5-314" aria-hidden="true" tabindex="-1"></a><span class="co"># Média (kPa → MPa)</span></span>
<span id="cb5-315"><a href="#cb5-315" aria-hidden="true" tabindex="-1"></a>media_B_MPa <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados_B) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-316"><a href="#cb5-316" aria-hidden="true" tabindex="-1"></a>media_B_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(media_B_MPa, <span class="dv">2</span>)</span>
<span id="cb5-317"><a href="#cb5-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-318"><a href="#cb5-318" aria-hidden="true" tabindex="-1"></a><span class="co"># Mediana (kPa → MPa)</span></span>
<span id="cb5-319"><a href="#cb5-319" aria-hidden="true" tabindex="-1"></a>mediana_B_MPa <span class="ot">&lt;-</span> <span class="fu">median</span>(dados_B) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-320"><a href="#cb5-320" aria-hidden="true" tabindex="-1"></a>mediana_B_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(mediana_B_MPa, <span class="dv">2</span>)</span>
<span id="cb5-321"><a href="#cb5-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-322"><a href="#cb5-322" aria-hidden="true" tabindex="-1"></a><span class="co"># Desvio Padrão (kPa → MPa)</span></span>
<span id="cb5-323"><a href="#cb5-323" aria-hidden="true" tabindex="-1"></a>desvio_B <span class="ot">&lt;-</span> <span class="fu">sd</span>(dados_B) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-324"><a href="#cb5-324" aria-hidden="true" tabindex="-1"></a>desvio_B_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(desvio_B, <span class="dv">2</span>)</span>
<span id="cb5-325"><a href="#cb5-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-326"><a href="#cb5-326" aria-hidden="true" tabindex="-1"></a><span class="co"># Variância (kPa² → MPa²)</span></span>
<span id="cb5-327"><a href="#cb5-327" aria-hidden="true" tabindex="-1"></a>variancia_B <span class="ot">&lt;-</span> <span class="fu">var</span>(dados_B) <span class="sc">/</span> (<span class="dv">1000</span><span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb5-328"><a href="#cb5-328" aria-hidden="true" tabindex="-1"></a>variancia_B_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(variancia_B, <span class="dv">2</span>)</span>
<span id="cb5-329"><a href="#cb5-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-330"><a href="#cb5-330" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficiente de Variação (mesmo em %)</span></span>
<span id="cb5-331"><a href="#cb5-331" aria-hidden="true" tabindex="-1"></a>cv_B <span class="ot">&lt;-</span> (<span class="fu">sd</span>(dados_B) <span class="sc">/</span> <span class="fu">mean</span>(dados_B)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb5-332"><a href="#cb5-332" aria-hidden="true" tabindex="-1"></a>cv_B_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(cv_B, <span class="dv">2</span>)</span>
<span id="cb5-333"><a href="#cb5-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-334"><a href="#cb5-334" aria-hidden="true" tabindex="-1"></a><span class="co"># Assimetria (adimensional)</span></span>
<span id="cb5-335"><a href="#cb5-335" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(dados_B)</span>
<span id="cb5-336"><a href="#cb5-336" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_B <span class="sc">-</span> <span class="fu">mean</span>(dados_B))<span class="sc">^</span><span class="dv">3</span>) <span class="sc">/</span> n</span>
<span id="cb5-337"><a href="#cb5-337" aria-hidden="true" tabindex="-1"></a>s3 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_B <span class="sc">-</span> <span class="fu">mean</span>(dados_B))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span>(<span class="dv">3</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb5-338"><a href="#cb5-338" aria-hidden="true" tabindex="-1"></a>assimetria_B <span class="ot">&lt;-</span> m3 <span class="sc">/</span> s3</span>
<span id="cb5-339"><a href="#cb5-339" aria-hidden="true" tabindex="-1"></a>assimetria_B_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(assimetria_B, <span class="dv">3</span>)</span>
<span id="cb5-340"><a href="#cb5-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-341"><a href="#cb5-341" aria-hidden="true" tabindex="-1"></a><span class="co"># Curtose (adimensional)</span></span>
<span id="cb5-342"><a href="#cb5-342" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_B <span class="sc">-</span> <span class="fu">mean</span>(dados_B))<span class="sc">^</span><span class="dv">4</span>) <span class="sc">/</span> n</span>
<span id="cb5-343"><a href="#cb5-343" aria-hidden="true" tabindex="-1"></a>s4 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_B <span class="sc">-</span> <span class="fu">mean</span>(dados_B))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb5-344"><a href="#cb5-344" aria-hidden="true" tabindex="-1"></a>curtose_B <span class="ot">&lt;-</span> m4 <span class="sc">/</span> s4</span>
<span id="cb5-345"><a href="#cb5-345" aria-hidden="true" tabindex="-1"></a>curtose_B_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(curtose_B, <span class="dv">3</span>)</span>
<span id="cb5-346"><a href="#cb5-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-347"><a href="#cb5-347" aria-hidden="true" tabindex="-1"></a><span class="co"># Mínimo (kPa → MPa)</span></span>
<span id="cb5-348"><a href="#cb5-348" aria-hidden="true" tabindex="-1"></a>min_B <span class="ot">&lt;-</span> <span class="fu">min</span>(dados_B) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-349"><a href="#cb5-349" aria-hidden="true" tabindex="-1"></a>min_B_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(min_B, <span class="dv">2</span>)</span>
<span id="cb5-350"><a href="#cb5-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-351"><a href="#cb5-351" aria-hidden="true" tabindex="-1"></a><span class="co"># Máximo (kPa → MPa)</span></span>
<span id="cb5-352"><a href="#cb5-352" aria-hidden="true" tabindex="-1"></a>max_B <span class="ot">&lt;-</span> <span class="fu">max</span>(dados_B) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-353"><a href="#cb5-353" aria-hidden="true" tabindex="-1"></a>max_B_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(max_B, <span class="dv">2</span>)</span>
<span id="cb5-354"><a href="#cb5-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-355"><a href="#cb5-355" aria-hidden="true" tabindex="-1"></a><span class="co"># Amplitude Total (kPa → MPa)</span></span>
<span id="cb5-356"><a href="#cb5-356" aria-hidden="true" tabindex="-1"></a>amplitude_B <span class="ot">&lt;-</span> (<span class="fu">max</span>(dados_B) <span class="sc">-</span> <span class="fu">min</span>(dados_B)) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-357"><a href="#cb5-357" aria-hidden="true" tabindex="-1"></a>amplitude_B_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(amplitude_B, <span class="dv">2</span>)</span>
<span id="cb5-358"><a href="#cb5-358" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-359"><a href="#cb5-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-362"><a href="#cb5-362" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb5-363"><a href="#cb5-363" aria-hidden="true" tabindex="-1"></a><span class="co"># ==================== GRUPO C ====================</span></span>
<span id="cb5-364"><a href="#cb5-364" aria-hidden="true" tabindex="-1"></a>dados_C <span class="ot">&lt;-</span> corposdeprova<span class="sc">$</span>Resistencia_kPa[corposdeprova<span class="sc">$</span>Grupo <span class="sc">==</span> <span class="st">"C"</span>]</span>
<span id="cb5-365"><a href="#cb5-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-366"><a href="#cb5-366" aria-hidden="true" tabindex="-1"></a><span class="co"># Média (kPa → MPa)</span></span>
<span id="cb5-367"><a href="#cb5-367" aria-hidden="true" tabindex="-1"></a>media_C_MPa <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados_C) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-368"><a href="#cb5-368" aria-hidden="true" tabindex="-1"></a>media_C_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(media_C_MPa, <span class="dv">2</span>)</span>
<span id="cb5-369"><a href="#cb5-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-370"><a href="#cb5-370" aria-hidden="true" tabindex="-1"></a><span class="co"># Mediana (kPa → MPa)</span></span>
<span id="cb5-371"><a href="#cb5-371" aria-hidden="true" tabindex="-1"></a>mediana_C_MPa <span class="ot">&lt;-</span> <span class="fu">median</span>(dados_C) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-372"><a href="#cb5-372" aria-hidden="true" tabindex="-1"></a>mediana_C_MPa_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(mediana_C_MPa, <span class="dv">2</span>)</span>
<span id="cb5-373"><a href="#cb5-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-374"><a href="#cb5-374" aria-hidden="true" tabindex="-1"></a><span class="co"># Desvio Padrão (kPa → MPa)</span></span>
<span id="cb5-375"><a href="#cb5-375" aria-hidden="true" tabindex="-1"></a>desvio_C <span class="ot">&lt;-</span> <span class="fu">sd</span>(dados_C) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-376"><a href="#cb5-376" aria-hidden="true" tabindex="-1"></a>desvio_C_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(desvio_C, <span class="dv">2</span>)</span>
<span id="cb5-377"><a href="#cb5-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-378"><a href="#cb5-378" aria-hidden="true" tabindex="-1"></a><span class="co"># Variância (kPa² → MPa²)</span></span>
<span id="cb5-379"><a href="#cb5-379" aria-hidden="true" tabindex="-1"></a>variancia_C <span class="ot">&lt;-</span> <span class="fu">var</span>(dados_C) <span class="sc">/</span> (<span class="dv">1000</span><span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb5-380"><a href="#cb5-380" aria-hidden="true" tabindex="-1"></a>variancia_C_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(variancia_C, <span class="dv">2</span>)</span>
<span id="cb5-381"><a href="#cb5-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-382"><a href="#cb5-382" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficiente de Variação (mesmo em %)</span></span>
<span id="cb5-383"><a href="#cb5-383" aria-hidden="true" tabindex="-1"></a>cv_C <span class="ot">&lt;-</span> (<span class="fu">sd</span>(dados_C) <span class="sc">/</span> <span class="fu">mean</span>(dados_C)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb5-384"><a href="#cb5-384" aria-hidden="true" tabindex="-1"></a>cv_C_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(cv_C, <span class="dv">2</span>)</span>
<span id="cb5-385"><a href="#cb5-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-386"><a href="#cb5-386" aria-hidden="true" tabindex="-1"></a><span class="co"># Assimetria (adimensional)</span></span>
<span id="cb5-387"><a href="#cb5-387" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(dados_C)</span>
<span id="cb5-388"><a href="#cb5-388" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_C <span class="sc">-</span> <span class="fu">mean</span>(dados_C))<span class="sc">^</span><span class="dv">3</span>) <span class="sc">/</span> n</span>
<span id="cb5-389"><a href="#cb5-389" aria-hidden="true" tabindex="-1"></a>s3 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_C <span class="sc">-</span> <span class="fu">mean</span>(dados_C))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span>(<span class="dv">3</span><span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb5-390"><a href="#cb5-390" aria-hidden="true" tabindex="-1"></a>assimetria_C <span class="ot">&lt;-</span> m3 <span class="sc">/</span> s3</span>
<span id="cb5-391"><a href="#cb5-391" aria-hidden="true" tabindex="-1"></a>assimetria_C_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(assimetria_C, <span class="dv">3</span>)</span>
<span id="cb5-392"><a href="#cb5-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-393"><a href="#cb5-393" aria-hidden="true" tabindex="-1"></a><span class="co"># Curtose (adimensional)</span></span>
<span id="cb5-394"><a href="#cb5-394" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados_C <span class="sc">-</span> <span class="fu">mean</span>(dados_C))<span class="sc">^</span><span class="dv">4</span>) <span class="sc">/</span> n</span>
<span id="cb5-395"><a href="#cb5-395" aria-hidden="true" tabindex="-1"></a>s4 <span class="ot">&lt;-</span> (<span class="fu">sum</span>((dados_C <span class="sc">-</span> <span class="fu">mean</span>(dados_C))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> n)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb5-396"><a href="#cb5-396" aria-hidden="true" tabindex="-1"></a>curtose_C <span class="ot">&lt;-</span> m4 <span class="sc">/</span> s4</span>
<span id="cb5-397"><a href="#cb5-397" aria-hidden="true" tabindex="-1"></a>curtose_C_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(curtose_C, <span class="dv">3</span>)</span>
<span id="cb5-398"><a href="#cb5-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-399"><a href="#cb5-399" aria-hidden="true" tabindex="-1"></a><span class="co"># Mínimo (kPa → MPa)</span></span>
<span id="cb5-400"><a href="#cb5-400" aria-hidden="true" tabindex="-1"></a>min_C <span class="ot">&lt;-</span> <span class="fu">min</span>(dados_C) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-401"><a href="#cb5-401" aria-hidden="true" tabindex="-1"></a>min_C_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(min_C, <span class="dv">2</span>)</span>
<span id="cb5-402"><a href="#cb5-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-403"><a href="#cb5-403" aria-hidden="true" tabindex="-1"></a><span class="co"># Máximo (kPa → MPa)</span></span>
<span id="cb5-404"><a href="#cb5-404" aria-hidden="true" tabindex="-1"></a>max_C <span class="ot">&lt;-</span> <span class="fu">max</span>(dados_C) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-405"><a href="#cb5-405" aria-hidden="true" tabindex="-1"></a>max_C_formatado <span class="ot">&lt;-</span> <span class="fu">round</span>(max_C, <span class="dv">2</span>)</span>
<span id="cb5-406"><a href="#cb5-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-407"><a href="#cb5-407" aria-hidden="true" tabindex="-1"></a><span class="co"># Amplitude Total (kPa → MPa)</span></span>
<span id="cb5-408"><a href="#cb5-408" aria-hidden="true" tabindex="-1"></a>amplitude_C <span class="ot">&lt;-</span> (<span class="fu">max</span>(dados_C) <span class="sc">-</span> <span class="fu">min</span>(dados_C)) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb5-409"><a href="#cb5-409" aria-hidden="true" tabindex="-1"></a>amplitude_C_formatada <span class="ot">&lt;-</span> <span class="fu">round</span>(amplitude_C, <span class="dv">2</span>)</span>
<span id="cb5-410"><a href="#cb5-410" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-411"><a href="#cb5-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-412"><a href="#cb5-412" aria-hidden="true" tabindex="-1"></a><span class="fu">### Análise prática de cada grupo</span></span>
<span id="cb5-413"><a href="#cb5-413" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb5-414"><a href="#cb5-414" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Estatística <span class="pp">|</span> Grupo A <span class="pp">|</span> Grupo B <span class="pp">|</span> Grupo C <span class="pp">|</span></span>
<span id="cb5-415"><a href="#cb5-415" aria-hidden="true" tabindex="-1"></a><span class="pp">|-------------|---------|---------|---------|</span></span>
<span id="cb5-416"><a href="#cb5-416" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Média (MPa) <span class="pp">|</span> <span class="in">`r media_A_MPa_formatada`</span> <span class="pp">|</span> <span class="in">`r media_B_MPa_formatada`</span> <span class="pp">|</span> <span class="in">`r media_C_MPa_formatada`</span> <span class="pp">|</span></span>
<span id="cb5-417"><a href="#cb5-417" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Mediana (MPa) <span class="pp">|</span> <span class="in">`r mediana_A_MPa_formatada`</span> <span class="pp">|</span> <span class="in">`r mediana_B_MPa_formatada`</span> <span class="pp">|</span> <span class="in">`r mediana_C_MPa_formatada`</span> <span class="pp">|</span></span>
<span id="cb5-418"><a href="#cb5-418" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Desvio Padrão (MPa) <span class="pp">|</span> <span class="in">`r desvio_A_formatado`</span> <span class="pp">|</span> <span class="in">`r desvio_B_formatado`</span> <span class="pp">|</span> <span class="in">`r desvio_C_formatado`</span> <span class="pp">|</span></span>
<span id="cb5-419"><a href="#cb5-419" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Variância (MPa²) <span class="pp">|</span> <span class="in">`r variancia_A_formatada`</span> <span class="pp">|</span> <span class="in">`r variancia_B_formatada`</span> <span class="pp">|</span> <span class="in">`r variancia_C_formatada`</span> <span class="pp">|</span></span>
<span id="cb5-420"><a href="#cb5-420" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> CV (%) <span class="pp">|</span> <span class="in">`r cv_A_formatado`</span> <span class="pp">|</span> <span class="in">`r cv_B_formatado`</span> <span class="pp">|</span> <span class="in">`r cv_C_formatado`</span> <span class="pp">|</span></span>
<span id="cb5-421"><a href="#cb5-421" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Assimetria <span class="pp">|</span> <span class="in">`r assimetria_A_formatada`</span> <span class="pp">|</span> <span class="in">`r assimetria_B_formatada`</span> <span class="pp">|</span> <span class="in">`r assimetria_C_formatada`</span> <span class="pp">|</span></span>
<span id="cb5-422"><a href="#cb5-422" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Curtose <span class="pp">|</span> <span class="in">`r curtose_A_formatada`</span> <span class="pp">|</span> <span class="in">`r curtose_B_formatada`</span> <span class="pp">|</span> <span class="in">`r curtose_C_formatada`</span> <span class="pp">|</span></span>
<span id="cb5-423"><a href="#cb5-423" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Mínimo (MPa) <span class="pp">|</span> <span class="in">`r min_A_formatado`</span> <span class="pp">|</span> <span class="in">`r min_B_formatado`</span> <span class="pp">|</span> <span class="in">`r min_C_formatado`</span> <span class="pp">|</span></span>
<span id="cb5-424"><a href="#cb5-424" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Máximo (MPa) <span class="pp">|</span> <span class="in">`r max_A_formatado`</span> <span class="pp">|</span> <span class="in">`r max_B_formatado`</span> <span class="pp">|</span> <span class="in">`r max_C_formatado`</span> <span class="pp">|</span></span>
<span id="cb5-425"><a href="#cb5-425" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Amplitude (MPa) <span class="pp">|</span> <span class="in">`r amplitude_A_formatada`</span> <span class="pp">|</span> <span class="in">`r amplitude_B_formatada`</span> <span class="pp">|</span> <span class="in">`r amplitude_C_formatada`</span> <span class="pp">|</span></span>
<span id="cb5-426"><a href="#cb5-426" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb5-427"><a href="#cb5-427" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Grupo A</span></span>
<span id="cb5-428"><a href="#cb5-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-429"><a href="#cb5-429" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-430"><a href="#cb5-430" aria-hidden="true" tabindex="-1"></a>O grupo A apresentou resistência média de <span class="in">`r media_A_MPa_formatada`</span> MPa e mediana de <span class="in">`r mediana_A_MPa_formatada`</span> MPa. A proximidade entre essas duas medidas é um primeiro indício de que a distribuição é equilibrada e não está sendo fortemente afetada por valores extremos.</span>
<span id="cb5-431"><a href="#cb5-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-432"><a href="#cb5-432" aria-hidden="true" tabindex="-1"></a>O coeficiente de assimetria foi:</span>
<span id="cb5-433"><a href="#cb5-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-434"><a href="#cb5-434" aria-hidden="true" tabindex="-1"></a><span class="in">`r assimetria_A_formatada`</span></span>
<span id="cb5-435"><a href="#cb5-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-436"><a href="#cb5-436" aria-hidden="true" tabindex="-1"></a>Como o resultado está muito próximo de zero, a distribuição do grupo A pode ser considerada aproximadamente simétrica. O pequeno sinal positivo indica uma tendência mínima de alongamento à direita, mas a magnitude é tão baixa que não possui relevância prática nesse conjunto.</span>
<span id="cb5-437"><a href="#cb5-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-438"><a href="#cb5-438" aria-hidden="true" tabindex="-1"></a>O desvio padrão foi de <span class="in">`r desvio_A_formatado`</span>, indicando o afastamento típico dos resultados em torno da média. A amplitude foi de <span class="in">`r amplitude_A_formatada`</span> MPa, correspondente à diferença entre o maior resultado,  <span class="in">`r max_A_formatado`</span> MPa, e o menor, <span class="in">`r min_A_formatado`</span> MPa.</span>
<span id="cb5-439"><a href="#cb5-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-440"><a href="#cb5-440" aria-hidden="true" tabindex="-1"></a>O coeficiente de variação foi:</span>
<span id="cb5-441"><a href="#cb5-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-442"><a href="#cb5-442" aria-hidden="true" tabindex="-1"></a><span class="in">`r cv_A_formatado`</span> %</span>
<span id="cb5-443"><a href="#cb5-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-444"><a href="#cb5-444" aria-hidden="true" tabindex="-1"></a>Isso significa que o desvio padrão corresponde a aproximadamente <span class="in">`r cv_A_formatado`</span> % O grupo apresenta, portanto, uma variabilidade relativamente pequena em comparação com seu nível médio de resistência.</span>
<span id="cb5-445"><a href="#cb5-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-446"><a href="#cb5-446" aria-hidden="true" tabindex="-1"></a>O excesso de curtose foi de <span class="in">`r curtose_A_formatada`</span> O resultado negativo sugere que, nessa amostra, os valores se apresentam de forma relativamente mais distribuída e com caudas mais leves do que a distribuição normal. Não foram identificados valores atípicos pelo critério do intervalo interquartil.</span>
<span id="cb5-447"><a href="#cb5-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-448"><a href="#cb5-448" aria-hidden="true" tabindex="-1"></a>Em suma, o grupo A apresentou resistência média de <span class="in">`r media_A_MPa_formatada`</span>, baixa variabilidade relativa, distribuição aproximadamente simétrica e ausência de indícios estatísticos de valores discrepantes. A média e a mediana são praticamente iguais, indicando que ambas representam adequadamente o centro dos resultados.</span>
<span id="cb5-449"><a href="#cb5-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-450"><a href="#cb5-450" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Grupo B</span></span>
<span id="cb5-451"><a href="#cb5-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-452"><a href="#cb5-452" aria-hidden="true" tabindex="-1"></a>O grupo B apresentou resistência média de <span class="in">`r media_B_MPa_formatada`</span> MPa e mediana de <span class="in">`r mediana_B_MPa_formatada`</span> MPa. Novamente, observa-se grande proximidade entre as duas medidas, indicando que a média não está sendo fortemente deslocada por valores extremos.</span>
<span id="cb5-453"><a href="#cb5-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-454"><a href="#cb5-454" aria-hidden="true" tabindex="-1"></a>O coeficiente de assimetria foi:</span>
<span id="cb5-455"><a href="#cb5-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-456"><a href="#cb5-456" aria-hidden="true" tabindex="-1"></a><span class="in">`r assimetria_B_formatada`</span></span>
<span id="cb5-457"><a href="#cb5-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-458"><a href="#cb5-458" aria-hidden="true" tabindex="-1"></a>O sinal positivo indica uma leve tendência de cauda à direita, causada pelos resultados mais elevados, como 35,670 MPa e 36,050 MPa. Entretanto, o valor de <span class="in">`r assimetria_B_formatada`</span> ainda é relativamente próximo de zero. Portanto, a assimetria pode ser considerada pequena.</span>
<span id="cb5-459"><a href="#cb5-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-460"><a href="#cb5-460" aria-hidden="true" tabindex="-1"></a>O grupo B apresentou o maior desvio padrão entre os três grupos:</span>
<span id="cb5-461"><a href="#cb5-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-462"><a href="#cb5-462" aria-hidden="true" tabindex="-1"></a><span class="in">`r desvio_B_formatado`</span> MPa</span>
<span id="cb5-463"><a href="#cb5-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-464"><a href="#cb5-464" aria-hidden="true" tabindex="-1"></a>Também apresentou a maior amplitude:</span>
<span id="cb5-465"><a href="#cb5-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-466"><a href="#cb5-466" aria-hidden="true" tabindex="-1"></a>A=<span class="in">`r max_B_formatado`</span>  - <span class="in">`r min_B_formatado`</span>=6,490 MPa</span>
<span id="cb5-467"><a href="#cb5-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-468"><a href="#cb5-468" aria-hidden="true" tabindex="-1"></a>Esses resultados indicam que o grupo B possui maior dispersão absoluta. O coeficiente de variação foi de <span class="in">`r cv_B_formatado`</span> %, também o maior entre os três grupos. Embora a diferença não seja muito elevada, o grupo B é relativamente o menos homogêneo.</span>
<span id="cb5-469"><a href="#cb5-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-470"><a href="#cb5-470" aria-hidden="true" tabindex="-1"></a>O excesso de curtose foi de<span class="in">`r curtose_B_formatada`</span>, indicando uma distribuição relativamente achatada e sem forte concentração de resultados extremos. Pelo critério do intervalo interquartil, também não foram identificados valores atípicos.</span>
<span id="cb5-471"><a href="#cb5-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-472"><a href="#cb5-472" aria-hidden="true" tabindex="-1"></a>Em suma, o grupo B apresentou resistência média de <span class="in">`r media_B_MPa_formatada`</span> MPa e leve assimetria positiva. Embora não tenham sido identificados valores discrepantes, o grupo apresentou a maior amplitude, o maior desvio padrão e o maior coeficiente de variação, sendo o grupo com maior variabilidade entre os corpos de prova.</span>
<span id="cb5-473"><a href="#cb5-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-474"><a href="#cb5-474" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Grupo C</span></span>
<span id="cb5-475"><a href="#cb5-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-476"><a href="#cb5-476" aria-hidden="true" tabindex="-1"></a>O grupo C apresentou a maior resistência média:</span>
<span id="cb5-477"><a href="#cb5-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-478"><a href="#cb5-478" aria-hidden="true" tabindex="-1"></a><span class="in">`r media_C_MPa_formatada`</span> MPa</span>
<span id="cb5-479"><a href="#cb5-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-480"><a href="#cb5-480" aria-hidden="true" tabindex="-1"></a>Sua mediana foi de <span class="in">`r mediana_C_MPa_formatada`</span> MPa, novamente muito próxima da média. Essa proximidade indica que a distribuição é equilibrada e que os valores altos ou baixos não estão deslocando significativamente a média.</span>
<span id="cb5-481"><a href="#cb5-481" aria-hidden="true" tabindex="-1"></a>O coeficiente de assimetria foi:</span>
<span id="cb5-482"><a href="#cb5-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-483"><a href="#cb5-483" aria-hidden="true" tabindex="-1"></a><span class="in">`r assimetria_C_formatada`</span></span>
<span id="cb5-484"><a href="#cb5-484" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-485"><a href="#cb5-485" aria-hidden="true" tabindex="-1"></a>O valor está praticamente igual a zero, indicando uma distribuição aproximadamente simétrica. Portanto, tanto a média quanto a mediana representam adequadamente o centro dos resultados do grupo C.</span>
<span id="cb5-486"><a href="#cb5-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-487"><a href="#cb5-487" aria-hidden="true" tabindex="-1"></a>O desvio padrão foi de <span class="in">`r desvio_C_formatado`</span> MPa, valor intermediário entre os grupos A e B. A amplitude foi:</span>
<span id="cb5-488"><a href="#cb5-488" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-489"><a href="#cb5-489" aria-hidden="true" tabindex="-1"></a>A=<span class="in">`r max_C_formatado`</span>-<span class="in">`r min_C_formatado`</span>=5,410" MPa"</span>
<span id="cb5-490"><a href="#cb5-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-491"><a href="#cb5-491" aria-hidden="true" tabindex="-1"></a>Entretanto, para comparar a homogeneidade dos grupos, o coeficiente de variação é mais informativo do que o desvio padrão isolado, porque leva em consideração a média de cada grupo. Para o grupo C:</span>
<span id="cb5-492"><a href="#cb5-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-493"><a href="#cb5-493" aria-hidden="true" tabindex="-1"></a>**CV=<span class="in">`r cv_C_formatado`</span> %</span>
<span id="cb5-494"><a href="#cb5-494" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-495"><a href="#cb5-495" aria-hidden="true" tabindex="-1"></a>Esse foi o menor coeficiente de variação entre os três grupos. Assim, apesar de o desvio padrão do grupo C ser maior que o do grupo A, sua dispersão é menor quando comparada proporcionalmente à respectiva média.</span>
<span id="cb5-496"><a href="#cb5-496" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-497"><a href="#cb5-497" aria-hidden="true" tabindex="-1"></a>O excesso de curtose foi de <span class="in">`r curtose_C_formatada`</span>, apontando uma distribuição relativamente mais achatada e sem caudas pesadas. Não foram identificados valores atípicos pelo critério do intervalo interquartil.</span>
<span id="cb5-498"><a href="#cb5-498" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-499"><a href="#cb5-499" aria-hidden="true" tabindex="-1"></a>Em suma, o grupo C apresentou a maior resistência média e o menor coeficiente de variação. Os dados possuem distribuição aproximadamente simétrica, sem evidência de valores discrepantes. Em termos relativos, o grupo C apresentou a maior homogeneidade entre os corpos de prova.</span>
<span id="cb5-500"><a href="#cb5-500" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-501"><a href="#cb5-501" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Comparação prática dos grupos</span></span>
<span id="cb5-502"><a href="#cb5-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-503"><a href="#cb5-503" aria-hidden="true" tabindex="-1"></a>A ordem das resistências médias foi:</span>
<span id="cb5-504"><a href="#cb5-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-505"><a href="#cb5-505" aria-hidden="true" tabindex="-1"></a>"Grupo C"&gt;"Grupo B"&gt;"Grupo A"</span>
<span id="cb5-506"><a href="#cb5-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-507"><a href="#cb5-507" aria-hidden="true" tabindex="-1"></a>As diferenças entre as médias foram:</span>
<span id="cb5-508"><a href="#cb5-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-509"><a href="#cb5-509" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Grupo B em relação ao A: **4,290 MPa, aproximadamente 15,23% superior;**</span>
<span id="cb5-510"><a href="#cb5-510" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Grupo C em relação ao A: **11,321 MPa, aproximadamente 40,20% superior;**</span>
<span id="cb5-511"><a href="#cb5-511" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Grupo C em relação ao B: **7,031 MPa, aproximadamente 21,66% superior.**</span>
<span id="cb5-512"><a href="#cb5-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-513"><a href="#cb5-513" aria-hidden="true" tabindex="-1"></a>Portanto, se os três grupos representam diferentes traços, materiais, idades de cura ou condições de fabricação, o grupo C apresentou o melhor resultado médio de resistência.</span>
<span id="cb5-514"><a href="#cb5-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-515"><a href="#cb5-515" aria-hidden="true" tabindex="-1"></a>Com relação à homogeneidade, observando-se o coeficiente de variação:</span>
<span id="cb5-516"><a href="#cb5-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-517"><a href="#cb5-517" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Grupo C = **4,20% - Mais homogêneo;**</span>
<span id="cb5-518"><a href="#cb5-518" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Grupo A = **5,07%;**</span>
<span id="cb5-519"><a href="#cb5-519" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Grupo B = **5,84% - Menos homogêneo.**</span>
<span id="cb5-520"><a href="#cb5-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-521"><a href="#cb5-521" aria-hidden="true" tabindex="-1"></a>Em resumo, o grupo C combina a maior resistência média com a menor dispersão relativa. </span>
<span id="cb5-522"><a href="#cb5-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-523"><a href="#cb5-523" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🧠 Considerações finais</span></span>
<span id="cb5-524"><a href="#cb5-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-525"><a href="#cb5-525" aria-hidden="true" tabindex="-1"></a>Os quatro primeiros capítulos do livro fornecem uma base importante para o estudo da Estatística aplicada. Inicialmente, são apresentados conceitos fundamentais, como população, amostra, variável e dado. Em seguida, o livro aborda a organização dos dados por meio de tabelas, frequências e representações gráficas. Depois, são estudadas medidas que resumem os dados, como média, mediana e moda, além de medidas que avaliam a variabilidade, como amplitude, variância, desvio padrão, coeficiente de variação e erro padrão da média. Além disso, a inclusão dos conceitos de assimetria e curtose amplia a análise descritiva, pois permite compreender melhor o formato da distribuição dos dados complementando as medidas de posição e dispersão e oferecendo uma visão mais completa sobre o comportamento dos dados.</span>
<span id="cb5-526"><a href="#cb5-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-527"><a href="#cb5-527" aria-hidden="true" tabindex="-1"></a>A introdução ao R mostra a importância do uso de ferramentas computacionais na Estatística. O R, em conjunto com o RStudio, permite realizar cálculos, organizar dados, construir gráficos e aplicar técnicas estatísticas com eficiência. Além disso, entender a sintaxe e a semântica do R é essencial para escrever comandos corretamente e interpretar o significado das operações realizadas. Assim, o aprendizado dos conceitos teóricos aliado ao uso de softwares estatísticos contribui para uma formação mais completa e aplicada, especialmente nas áreas de Engenharia e Ciências.</span>
<span id="cb5-528"><a href="#cb5-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-529"><a href="#cb5-529" aria-hidden="true" tabindex="-1"></a>Conclui-se, com base na Estatística Descritiva, que o grupo C apresentou a maior resistência média e o menor coeficiente de variação, enquanto o grupo B apresentou resistência superior à do grupo A, mas também a maior dispersão. Entretanto, essas medidas permitem apenas organizar, resumir e comparar os dados observados, não sendo suficientes para generalizar os resultados ou tomar decisões sobre a população. Para verificar se as diferenças encontradas são estatisticamente significativas, torna-se necessária a aplicação da Estatística Inferencial, por meio de métodos como intervalos de confiança, testes de hipóteses e análise de variância. A decisão sobre o atendimento aos requisitos do projeto também deve considerar a resistência especificada, a idade de rompimento, o material, o plano de amostragem, a quantidade de exemplares e os critérios da norma técnica aplicável. Essas análises serão abordadas nos próximos relatórios. </span>
<span id="cb5-530"><a href="#cb5-530" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-531"><a href="#cb5-531" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-532"><a href="#cb5-532" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📖 Referências</span></span>
<span id="cb5-533"><a href="#cb5-533" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-534"><a href="#cb5-534" aria-hidden="true" tabindex="-1"></a>Depois de inserido as informaçõe no arquivo **referencias.bib**, use:</span>
<span id="cb5-535"><a href="#cb5-535" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-536"><a href="#cb5-536" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Segundo @Rbasico2022</span>
<span id="cb5-537"><a href="#cb5-537" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Tudo é um objeto em R <span class="co">[</span><span class="ot">@Rbasico2022</span><span class="co">]</span></span>
<span id="cb5-538"><a href="#cb5-538" aria-hidden="true" tabindex="-1"></a>@batista2026EPAEC</span>
</code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>